/**
 * anagramsLogic.js — Core Engine & Word Lists for Anagrams (Words & Reasoning)
 * Supports Beginner (5-letter root), Intermediate (6-letter root), and Master (7-letter root).
 */

export const DIFFICULTY_TIERS = {
  beginner: {
    id: 'beginner',
    label: 'Beginner',
    rootLength: 5,
    minWords: 4,
    description: '5-letter root words with 5–8 discovery targets',
  },
  intermediate: {
    id: 'intermediate',
    label: 'Intermediate',
    rootLength: 6,
    minWords: 6,
    description: '6-letter root words with 7–10 discovery targets',
  },
  master: {
    id: 'master',
    label: 'Master',
    rootLength: 7,
    minWords: 8,
    description: '7-letter root words with 9–14 discovery targets',
  },
};

/**
 * Curated puzzles with verified valid English anagram sub-words.
 */
export const ANAGRAM_PUZZLES = {
  beginner: [
    {
      id: 'beg-heart',
      root: 'HEART',
      targets: ['ART', 'EAR', 'HAT', 'TEA', 'HEAR', 'HEAT', 'HATE', 'EARTH', 'HEART'],
      extras: ['ERA', 'RAT', 'TAR', 'EAT', 'ATE', 'HARE', 'TEAR', 'RATE'],
    },
    {
      id: 'beg-stone',
      root: 'STONE',
      targets: ['ONE', 'NOT', 'SON', 'SET', 'TOE', 'NOSE', 'NOTE', 'TONE', 'NEST', 'STONE'],
      extras: ['EON', 'TON', 'NET', 'TEN', 'SENT', 'TOES', 'ONSET'],
    },
    {
      id: 'beg-bread',
      root: 'BREAD',
      targets: ['BED', 'BAD', 'BAR', 'RED', 'EAR', 'BEAR', 'BARE', 'DEAR', 'DARE', 'READ', 'BREAD'],
      extras: ['ERA', 'BEAD', 'BARD', 'BEARD'],
    },
    {
      id: 'beg-plant',
      root: 'PLANT',
      targets: ['ANT', 'PAN', 'NAP', 'TAP', 'PLAN', 'PANT', 'PLANT'],
      extras: ['PAT', 'TAN', 'PLAT'],
    },
    {
      id: 'beg-ocean',
      root: 'OCEAN',
      targets: ['ACE', 'CAN', 'ONE', 'ACNE', 'CANE', 'CONE', 'ONCE', 'OCEAN'],
      extras: ['EON'],
    },
  ],

  intermediate: [
    {
      id: 'int-silver',
      root: 'SILVER',
      targets: ['SIR', 'LIE', 'VIE', 'EVIL', 'LIVE', 'VILE', 'VEIL', 'RISE', 'LIVER', 'SILVER'],
      extras: ['SIRE'],
    },
    {
      id: 'int-garden',
      root: 'GARDEN',
      targets: ['AGE', 'DEN', 'EAR', 'END', 'RED', 'DARE', 'DEAR', 'GEAR', 'NEAR', 'READ', 'DANGER', 'GARDEN'],
      extras: ['ERA', 'RAG', 'AND', 'EARN', 'RANG'],
    },
    {
      id: 'int-planet',
      root: 'PLANET',
      targets: ['ANT', 'LET', 'NET', 'PAN', 'PET', 'TAP', 'LANE', 'LATE', 'LEAP', 'NEAT', 'PALE', 'PLAN', 'TALE', 'PLANET'],
      extras: ['NAP', 'PAT', 'TAN', 'TEN', 'ATE', 'EAT', 'TEA', 'PANT', 'PLEA', 'LEAN'],
    },
    {
      id: 'int-castle',
      root: 'CASTLE',
      targets: ['ACT', 'ALE', 'CAT', 'LET', 'SEA', 'SET', 'CASE', 'CAST', 'EAST', 'LATE', 'SALE', 'SEAT', 'TALE', 'LEAST', 'SCALE', 'CASTLE'],
      extras: ['TEA', 'EAT', 'ATE', 'STALE'],
    },
    {
      id: 'int-spring',
      root: 'SPRING',
      targets: ['PIG', 'PIN', 'RIG', 'SIN', 'SIP', 'GRIP', 'PING', 'RING', 'SIGN', 'SING', 'SPIN', 'SPRING'],
      extras: ['NIP'],
    },
  ],

  master: [
    {
      id: 'mst-harvest',
      root: 'HARVEST',
      targets: ['ART', 'EAR', 'HAT', 'RAT', 'SEA', 'SET', 'TEA', 'HATE', 'HEAR', 'HEAT', 'REST', 'SAVE', 'STAR', 'TEAR', 'VASE', 'VEST', 'EARTH', 'HEART', 'SHARE', 'STARE', 'HARVEST'],
      extras: ['ERA', 'TAR', 'EAT', 'ATE', 'HARE', 'RATE'],
    },
    {
      id: 'mst-blossom',
      root: 'BLOSSOM',
      targets: ['BOO', 'LOB', 'MOO', 'SOB', 'BOOM', 'BOSS', 'LOOM', 'MOSS', 'SOLO', 'BLOOM', 'BLOSSOM'],
      extras: ['SLOB'],
    },
    {
      id: 'mst-miracle',
      root: 'MIRACLE',
      targets: ['AIM', 'ARM', 'EAR', 'ICE', 'LIE', 'RIM', 'ACRE', 'CALM', 'CARE', 'LIME', 'MALE', 'MILE', 'RACE', 'CLAIM', 'CLEAR', 'REALM', 'MIRACLE'],
      extras: ['ERA', 'CRAM'],
    },
    {
      id: 'mst-weather',
      root: 'WEATHER',
      targets: ['AWE', 'HAT', 'RAW', 'THE', 'WAR', 'WET', 'HARE', 'HATE', 'HEAR', 'HEAT', 'RATE', 'TEAR', 'WEAR', 'EARTH', 'HEART', 'WATER', 'WHEAT', 'WEATHER'],
      extras: ['EAR', 'ERA', 'ART', 'RAT', 'TAR', 'TEA', 'EAT', 'ATE'],
    },
  ],
};

/**
 * Comprehensive English Word Dictionary for Anagrams
 * 7262 verified words across lengths 3, 4, 5, 6, and 7.
 */
export const ANAGRAM_DICTIONARY = new Set([
  'ABACK', 'ABASE', 'ABATE', 'ABBEY', 'ABIDE', 'ABILITY', 'ABLE', 'ABLY', 'ABOUT', 'ABOVE', 'ABROAD', 'ABSENCE',
  'ABSENT', 'ABSORB', 'ABYSS', 'ACADEMY', 'ACCENT', 'ACCEPT', 'ACCESS', 'ACCORD', 'ACCOUNT', 'ACCUSED', 'ACE', 'ACED',
  'ACES', 'ACHE', 'ACHIEVE', 'ACID', 'ACNE', 'ACORN', 'ACQUIRE', 'ACRE', 'ACRID', 'ACROSS', 'ACT', 'ACTING',
  'ACTION', 'ACTIVE', 'ACTOR', 'ACTS', 'ACTUAL', 'ACUTE', 'ADAPT', 'ADD', 'ADDRESS', 'ADHERE', 'ADJUST', 'ADMIRE',
  'ADMIT', 'ADOPT', 'ADORE', 'ADULT', 'ADVANCE', 'ADVENT', 'ADVERSE', 'ADVICE', 'ADVISE', 'ADVISED', 'ADVISER', 'AERIAL',
  'AFFAIR', 'AFFECT', 'AFFORD', 'AFRAID', 'AFTER', 'AGAIN', 'AGAINST', 'AGE', 'AGED', 'AGENCY', 'AGENDA', 'AGES',
  'AGILE', 'AGO', 'AGONY', 'AGREED', 'AHEAD', 'AHEM', 'AID', 'AIDE', 'AIDS', 'AIM', 'AIMS', 'AIR',
  'AIRLINE', 'AIRPORT', 'AIRS', 'AIRY', 'AJAR', 'AKIN', 'ALAS', 'ALBEIT', 'ALBUM', 'ALCOHOL', 'ALE', 'ALERT',
  'ALIEN', 'ALIGHT', 'ALIKE', 'ALIVE', 'ALL', 'ALLEGE', 'ALLEGED', 'ALLIED', 'ALLOW', 'ALLY', 'ALMOST', 'ALMS',
  'ALOE', 'ALONE', 'ALONG', 'ALOOF', 'ALOUD', 'ALPHA', 'ALREADY', 'ALSO', 'ALTAR', 'ALTER', 'ALTERED', 'ALTO',
  'ALWAYS', 'AMASS', 'AMATEUR', 'AMAZED', 'AMAZING', 'AMBER', 'AMBUSH', 'AMEN', 'AMEND', 'AMENDS', 'AMID', 'AMIDST',
  'AMISS', 'AMMO', 'AMOK', 'AMONG', 'AMONGST', 'AMOUNT', 'AMP', 'AMPLE', 'AMPS', 'AMUSED', 'ANALYZE', 'ANCHOR',
  'ANCIENT', 'AND', 'ANEW', 'ANGEL', 'ANGELIC', 'ANGELS', 'ANGER', 'ANGERS', 'ANGLE', 'ANGLES', 'ANGRY', 'ANIMAL',
  'ANIMALS', 'ANKLE', 'ANNEX', 'ANNOY', 'ANNUAL', 'ANNUL', 'ANOTHER', 'ANSWER', 'ANT', 'ANTE', 'ANTI', 'ANTIC',
  'ANTS', 'ANVIL', 'ANXIETY', 'ANY', 'ANYBODY', 'ANYHOW', 'ANYMORE', 'ANYONE', 'ANYWAY', 'APART', 'APE', 'APES',
  'APEX', 'APEXS', 'APHID', 'APOLOGY', 'APPAREL', 'APPEAL', 'APPEALS', 'APPEAR', 'APPEARS', 'APPLE', 'APPLIED', 'APPLY',
  'APPOINT', 'APPROVE', 'APPS', 'APRON', 'APT', 'APTLY', 'ARBOR', 'ARC', 'ARCH', 'ARCHIVE', 'ARCTIC', 'ARDENT',
  'ARDOR', 'ARE', 'AREA', 'AREAS', 'ARGUE', 'ARGUED', 'ARISE', 'ARK', 'ARM', 'ARMOR', 'ARMY', 'AROMA',
  'AROSE', 'AROUND', 'ARRANGE', 'ARRAY', 'ARREST', 'ARRIVAL', 'ARRIVE', 'ARRIVED', 'ARROW', 'ARROWS', 'ARSON', 'ART',
  'ARTERY', 'ARTISAN', 'ARTIST', 'ARTISTS', 'ARTS', 'ARTY', 'ASCENT', 'ASH', 'ASHAMED', 'ASHEN', 'ASHY', 'ASIDE',
  'ASK', 'ASKEW', 'ASPECT', 'ASPECTS', 'ASSAULT', 'ASSERT', 'ASSESS', 'ASSET', 'ASSIGN', 'ASSIST', 'ASSUME', 'ASSUMED',
  'ASSURE', 'ASSURES', 'ASTRAY', 'ATE', 'ATHLETE', 'ATOLL', 'ATOM', 'ATOMIC', 'ATOMICS', 'ATONE', 'ATTACH', 'ATTACK',
  'ATTAIN', 'ATTEMPT', 'ATTEND', 'ATTIC', 'ATTRACT', 'AUCTION', 'AUDIO', 'AUDIT', 'AUNT', 'AUNTY', 'AURA', 'AUTHOR',
  'AUTO', 'AUTUMN', 'AVAIL', 'AVENUE', 'AVERAGE', 'AVERT', 'AVIATOR', 'AVID', 'AVOID', 'AVOW', 'AWAIT', 'AWAKE',
  'AWARD', 'AWARDED', 'AWARE', 'AWASH', 'AWAY', 'AWE', 'AWFUL', 'AWHILE', 'AXE', 'AXES', 'AXIAL', 'AXIOM',
  'AXIS', 'AXLE', 'AYE', 'AZURE', 'BABE', 'BABY', 'BACK', 'BACKED', 'BACON', 'BAD', 'BADE', 'BADGE',
  'BADGER', 'BAG', 'BAGEL', 'BAGS', 'BAIL', 'BAIT', 'BAKE', 'BAKER', 'BAKERY', 'BALANCE', 'BALD', 'BALDY',
  'BALE', 'BALL', 'BALLOON', 'BALLOT', 'BALM', 'BALMY', 'BAMBOO', 'BAN', 'BANANA', 'BAND', 'BANE', 'BANG',
  'BANJO', 'BANK', 'BANKER', 'BANKING', 'BANNER', 'BANS', 'BAR', 'BARB', 'BARD', 'BARE', 'BARELY', 'BARGAIN',
  'BARGE', 'BARK', 'BARN', 'BARON', 'BARREL', 'BARRIER', 'BARS', 'BARTER', 'BASE', 'BASH', 'BASIC', 'BASIL',
  'BASIN', 'BASIS', 'BASK', 'BASKET', 'BASS', 'BAT', 'BATH', 'BATHE', 'BATON', 'BATS', 'BATTERY', 'BATTLE',
  'BAWL', 'BAY', 'BAYS', 'BEACH', 'BEACON', 'BEAD', 'BEADY', 'BEAK', 'BEAM', 'BEAN', 'BEAR', 'BEARD',
  'BEARING', 'BEAST', 'BEAT', 'BEATING', 'BEAUTY', 'BECAUSE', 'BECOME', 'BECOMES', 'BED', 'BEDROOM', 'BEDS', 'BEE',
  'BEECH', 'BEEF', 'BEEFY', 'BEEN', 'BEEP', 'BEER', 'BEES', 'BEET', 'BEFORE', 'BEG', 'BEGET', 'BEGIN',
  'BEGS', 'BEHALF', 'BEHAVE', 'BEHIND', 'BEHOLD', 'BEING', 'BELCH', 'BELIE', 'BELIEF', 'BELIEFS', 'BELIEVE', 'BELL',
  'BELLE', 'BELLY', 'BELONG', 'BELONGS', 'BELOW', 'BELT', 'BENCH', 'BEND', 'BENEATH', 'BENEFIT', 'BENIGN', 'BENT',
  'BERET', 'BERG', 'BERRY', 'BERTH', 'BESET', 'BESIDE', 'BESIDES', 'BEST', 'BESTOW', 'BET', 'BETA', 'BETS',
  'BETTER', 'BETWEEN', 'BEVEL', 'BEVY', 'BEWARE', 'BEYOND', 'BIAS', 'BIASED', 'BIBLE', 'BICEP', 'BICKER', 'BICYCLE',
  'BID', 'BIDDY', 'BIDE', 'BIG', 'BIGGER', 'BIGOT', 'BIKE', 'BILE', 'BILGE', 'BILL', 'BIN', 'BINARY',
  'BIND', 'BINDING', 'BINGE', 'BINGO', 'BIOLOGY', 'BIRCH', 'BIRD', 'BIRTH', 'BISHOP', 'BISON', 'BIT', 'BITCH',
  'BITE', 'BITER', 'BITS', 'BITTER', 'BLAB', 'BLACK', 'BLADE', 'BLADES', 'BLAH', 'BLAME', 'BLAND', 'BLANK',
  'BLANKET', 'BLANKS', 'BLARE', 'BLAST', 'BLASTS', 'BLAZE', 'BLAZES', 'BLEAK', 'BLEAT', 'BLED', 'BLEED', 'BLEEP',
  'BLEND', 'BLESS', 'BLEW', 'BLIMP', 'BLIND', 'BLINDS', 'BLINK', 'BLIP', 'BLISS', 'BLOB', 'BLOC', 'BLOCK',
  'BLOCKS', 'BLOKE', 'BLOND', 'BLONDE', 'BLOOD', 'BLOOM', 'BLOOMS', 'BLOSSOM', 'BLOT', 'BLOUSE', 'BLOW', 'BLOWN',
  'BLUE', 'BLUFF', 'BLUNT', 'BLUR', 'BLURB', 'BLURT', 'BLUSH', 'BOA', 'BOAR', 'BOARD', 'BOARDED', 'BOARDS',
  'BOAST', 'BOASTED', 'BOASTS', 'BOAT', 'BOATING', 'BOB', 'BOBBY', 'BODE', 'BODILY', 'BODY', 'BOG', 'BOGS',
  'BOIL', 'BOILER', 'BOLD', 'BOLE', 'BOLL', 'BOLT', 'BOMB', 'BOND', 'BONDING', 'BONE', 'BONEY', 'BONUS',
  'BONY', 'BOO', 'BOOK', 'BOOKING', 'BOOM', 'BOON', 'BOOR', 'BOOST', 'BOOT', 'BOOTH', 'BOOTY', 'BOOZE',
  'BORDER', 'BORDERS', 'BORE', 'BORING', 'BORN', 'BORROW', 'BOSOM', 'BOSS', 'BOSSY', 'BOTCH', 'BOTH', 'BOTHER',
  'BOTTLE', 'BOTTLES', 'BOTTOM', 'BOUGH', 'BOUNCE', 'BOUNCED', 'BOUND', 'BOUNDED', 'BOUNDS', 'BOUNTY', 'BOUT', 'BOW',
  'BOWEL', 'BOWL', 'BOWLING', 'BOWS', 'BOX', 'BOXER', 'BOY', 'BOYS', 'BRA', 'BRACE', 'BRACKET', 'BRAD',
  'BRAG', 'BRAID', 'BRAIN', 'BRAKE', 'BRAN', 'BRANCH', 'BRAND', 'BRANDS', 'BRAS', 'BRASS', 'BRAT', 'BRAVE',
  'BRAVERY', 'BRAVO', 'BRAWL', 'BRAWN', 'BRAY', 'BREACH', 'BREAD', 'BREADS', 'BREADTH', 'BREAK', 'BREAKS', 'BREATH',
  'BREATHE', 'BRED', 'BREED', 'BREEDS', 'BREEZE', 'BREW', 'BRIAR', 'BRIBE', 'BRICK', 'BRICKS', 'BRIDAL', 'BRIDE',
  'BRIDGE', 'BRIDGES', 'BRIEF', 'BRIGHT', 'BRIGHTS', 'BRIM', 'BRINE', 'BRING', 'BRINGS', 'BRINK', 'BRINY', 'BRISK',
  'BRITISH', 'BROAD', 'BROADEN', 'BROG', 'BROIL', 'BROKE', 'BROKEN', 'BRONZE', 'BROOD', 'BROOK', 'BROOM', 'BROTH',
  'BROTHER', 'BROW', 'BROWN', 'BROWSE', 'BRUNT', 'BRUSH', 'BRUTAL', 'BUBBLE', 'BUCK', 'BUCKET', 'BUCKETS', 'BUD',
  'BUDDY', 'BUDGE', 'BUDGET', 'BUDS', 'BUFF', 'BUFFALO', 'BUFFET', 'BUG', 'BUGGY', 'BUGS', 'BUILD', 'BUILDER',
  'BUILDS', 'BUILT', 'BULB', 'BULGE', 'BULK', 'BULKY', 'BULL', 'BULLET', 'BULLY', 'BUMP', 'BUMS', 'BUN',
  'BUNCH', 'BUNDLE', 'BUNK', 'BUNNY', 'BUNS', 'BUNT', 'BUOY', 'BURDEN', 'BUREAU', 'BURIAL', 'BURLY', 'BURN',
  'BURNING', 'BURNT', 'BURP', 'BURR', 'BURRO', 'BURST', 'BURY', 'BUS', 'BUSH', 'BUSHES', 'BUSHY', 'BUSY',
  'BUT', 'BUTCH', 'BUTLER', 'BUTT', 'BUTTE', 'BUTTER', 'BUTTON', 'BUY', 'BUYER', 'BUYERS', 'BUYS', 'BUZZ',
  'BYE', 'BYES', 'BYTE', 'CAB', 'CABIN', 'CABINET', 'CABLE', 'CABLES', 'CABS', 'CACAO', 'CACHE', 'CACTI',
  'CACTUS', 'CADDY', 'CADET', 'CAFE', 'CAGE', 'CAGEY', 'CAIRN', 'CAKE', 'CALF', 'CALIBER', 'CALL', 'CALLING',
  'CALM', 'CALORIE', 'CAM', 'CAME', 'CAMEL', 'CAMEO', 'CAMERA', 'CAMERAS', 'CAMP', 'CAMPING', 'CAMPUS', 'CAMS',
  'CAN', 'CANAL', 'CANCEL', 'CANCER', 'CANDID', 'CANDLE', 'CANDLES', 'CANDY', 'CANE', 'CANNON', 'CANOE', 'CANON',
  'CANOPY', 'CANS', 'CANVAS', 'CANYON', 'CAP', 'CAPABLE', 'CAPE', 'CAPER', 'CAPS', 'CAPTAIN', 'CAPTURE', 'CAPUT',
  'CAR', 'CARAT', 'CARAVAN', 'CARBON', 'CARD', 'CARE', 'CAREER', 'CAREERS', 'CAREFUL', 'CARESS', 'CARGO', 'CAROL',
  'CARP', 'CARPET', 'CARPETS', 'CARRIER', 'CARROT', 'CARROTS', 'CARRY', 'CARS', 'CART', 'CARVE', 'CASE', 'CASH',
  'CASINO', 'CASK', 'CAST', 'CASTE', 'CASTING', 'CASTLE', 'CASTLES', 'CASUAL', 'CASUALS', 'CAT', 'CATALOG', 'CATCH',
  'CATER', 'CATERER', 'CATS', 'CATTLE', 'CATTY', 'CAUGHT', 'CAULK', 'CAUSAL', 'CAUSE', 'CAUSES', 'CAUTION', 'CAVE',
  'CAVEAT', 'CAVERN', 'CAVERNS', 'CAVIL', 'CEASE', 'CEASED', 'CEDAR', 'CEDARS', 'CEDE', 'CEILING', 'CELL', 'CELLAR',
  'CELLO', 'CEMENT', 'CENSOR', 'CENSUS', 'CENT', 'CENTER', 'CENTRAL', 'CENTRE', 'CENTURY', 'CERTAIN', 'CHAD', 'CHAFE',
  'CHAFF', 'CHAIN', 'CHAINS', 'CHAIR', 'CHAIRS', 'CHALK', 'CHAMBER', 'CHAMP', 'CHANCE', 'CHANGE', 'CHANNEL', 'CHANT',
  'CHAOS', 'CHAPEL', 'CHAPTER', 'CHARD', 'CHARGE', 'CHARGES', 'CHARITY', 'CHARM', 'CHARMED', 'CHARMS', 'CHART', 'CHARTER',
  'CHARTS', 'CHASE', 'CHASED', 'CHASING', 'CHASM', 'CHASMS', 'CHEAP', 'CHEAPER', 'CHEAT', 'CHEATS', 'CHECK', 'CHECKED',
  'CHECKER', 'CHECKS', 'CHEEK', 'CHEEKS', 'CHEER', 'CHEERED', 'CHEERS', 'CHEESE', 'CHEF', 'CHERRY', 'CHESS', 'CHEST',
  'CHESTS', 'CHEW', 'CHICK', 'CHICKEN', 'CHIEF', 'CHIEFS', 'CHILD', 'CHILI', 'CHILL', 'CHIME', 'CHIMP', 'CHIN',
  'CHINA', 'CHINK', 'CHIP', 'CHIRP', 'CHIT', 'CHIVE', 'CHOCK', 'CHOICE', 'CHOICES', 'CHOIR', 'CHOKE', 'CHOOSE',
  'CHOP', 'CHORAL', 'CHORD', 'CHORE', 'CHORUS', 'CHOSE', 'CHOSEN', 'CHRONIC', 'CHUCK', 'CHUM', 'CHUMP', 'CHUNK',
  'CHURCH', 'CHURN', 'CHUTE', 'CIDER', 'CIGAR', 'CINCH', 'CINEMA', 'CIRCA', 'CIRCLE', 'CIRCLES', 'CIRCUIT', 'CIRCUS',
  'CITE', 'CITIZEN', 'CITY', 'CIVIC', 'CIVIL', 'CLACK', 'CLAD', 'CLAIM', 'CLAIMS', 'CLAM', 'CLAMOR', 'CLAMP',
  'CLAMS', 'CLAN', 'CLANG', 'CLANK', 'CLAP', 'CLARITY', 'CLASH', 'CLASP', 'CLASS', 'CLASSIC', 'CLAUSE', 'CLAW',
  'CLAY', 'CLEAN', 'CLEANED', 'CLEANER', 'CLEAR', 'CLEARED', 'CLEARS', 'CLEAT', 'CLEF', 'CLEFT', 'CLERGY', 'CLERK',
  'CLERKS', 'CLEVER', 'CLICK', 'CLIENT', 'CLIFF', 'CLIFFS', 'CLIMATE', 'CLIMAX', 'CLIMB', 'CLIMBED', 'CLING', 'CLINIC',
  'CLINICS', 'CLINK', 'CLIP', 'CLOAK', 'CLOCK', 'CLOCKS', 'CLOD', 'CLOG', 'CLONE', 'CLONES', 'CLOP', 'CLOSE',
  'CLOSED', 'CLOSER', 'CLOSET', 'CLOSING', 'CLOT', 'CLOTH', 'CLOTHE', 'CLOTHED', 'CLOTHES', 'CLOTHS', 'CLOUD', 'CLOUDS',
  'CLOUT', 'CLOVE', 'CLOVER', 'CLOWN', 'CLUB', 'CLUCK', 'CLUE', 'CLUED', 'CLUES', 'CLUMP', 'CLUMPS', 'CLUNG',
  'CLUSTER', 'CLUTCH', 'COACH', 'COACHED', 'COAL', 'COARSE', 'COAST', 'COASTAL', 'COASTS', 'COAT', 'COAX', 'COB',
  'COBALT', 'COBRA', 'COCK', 'COCOA', 'COD', 'CODE', 'COED', 'COFFEE', 'COG', 'COGNAC', 'COHORT', 'COIL',
  'COIN', 'COIR', 'COLD', 'COLDER', 'COLE', 'COLLAR', 'COLLEGE', 'COLON', 'COLONY', 'COLOR', 'COLORS', 'COLT',
  'COLUMN', 'COMA', 'COMB', 'COMBAT', 'COMBED', 'COMBINE', 'COME', 'COMEDY', 'COMET', 'COMETS', 'COMFORT', 'COMFY',
  'COMIC', 'COMICS', 'COMING', 'COMMA', 'COMMAND', 'COMMENT', 'COMMON', 'COMMONS', 'COMPACT', 'COMPANY', 'COMPARE', 'COMPASS',
  'COMPETE', 'COMPLEX', 'COMPLY', 'COMPOSE', 'COMPUTE', 'CON', 'CONCEAL', 'CONCERN', 'CONCERT', 'CONCH', 'CONCUR', 'CONDO',
  'CONDOR', 'CONDUCT', 'CONE', 'CONFER', 'CONFESS', 'CONFIRM', 'CONFUSE', 'CONIC', 'CONNECT', 'CONSENT', 'CONSIST', 'CONSUL',
  'CONTAIN', 'CONTENT', 'CONTEST', 'CONTEXT', 'CONTROL', 'CONVERT', 'CONVEX', 'CONVEY', 'CONVOY', 'COO', 'COOK', 'COOKED',
  'COOKING', 'COOL', 'COOLER', 'COOLING', 'COON', 'COOP', 'COOT', 'COP', 'COPE', 'COPIED', 'COPING', 'COPPER',
  'COPS', 'CORAL', 'CORALS', 'CORD', 'CORE', 'CORK', 'CORN', 'CORNER', 'CORNY', 'CORPS', 'CORPSE', 'CORPUS',
  'CORRECT', 'CORRUPT', 'COST', 'COSTING', 'COSTLY', 'COSTUME', 'COSY', 'COT', 'COTE', 'COTTAGE', 'COTTON', 'COUCH',
  'COUGH', 'COULD', 'COUNSEL', 'COUNT', 'COUNTER', 'COUNTRY', 'COUNTY', 'COUP', 'COUPE', 'COUPLE', 'COUPLES', 'COUPON',
  'COURAGE', 'COURIER', 'COURSE', 'COURT', 'COURTS', 'COUSIN', 'COUSINS', 'COVE', 'COVEN', 'COVER', 'COVERED', 'COVERS',
  'COVET', 'COVEY', 'COW', 'COWBOY', 'COWER', 'COWL', 'COWS', 'COY', 'COZY', 'CRAB', 'CRACK', 'CRACKED',
  'CRADLE', 'CRAFT', 'CRAFTED', 'CRAFTS', 'CRAG', 'CRAM', 'CRAMP', 'CRANE', 'CRANES', 'CRANING', 'CRANK', 'CRAP',
  'CRASH', 'CRASHED', 'CRASS', 'CRATE', 'CRATER', 'CRAVE', 'CRAVEN', 'CRAW', 'CRAWL', 'CRAYON', 'CRAZE', 'CRAZY',
  'CREAK', 'CREAM', 'CREAMS', 'CREASE', 'CREATE', 'CREATES', 'CREATOR', 'CREDIT', 'CREDITS', 'CREDO', 'CREED', 'CREEDS',
  'CREEK', 'CREEKS', 'CREEP', 'CREEPS', 'CREME', 'CREPE', 'CREPT', 'CRESS', 'CREST', 'CREW', 'CRIB', 'CRICK',
  'CRICKET', 'CRIED', 'CRIER', 'CRIES', 'CRIME', 'CRIMES', 'CRIMP', 'CRIPPLE', 'CRISIS', 'CRISP', 'CRITIC', 'CRITICS',
  'CROAK', 'CROCK', 'CRONE', 'CRONY', 'CROOK', 'CROOKS', 'CROP', 'CROSS', 'CROSSES', 'CROUP', 'CROW', 'CROWD',
  'CROWDED', 'CROWDS', 'CROWN', 'CROWNS', 'CRUCIAL', 'CRUD', 'CRUDE', 'CRUEL', 'CRUISE', 'CRUMB', 'CRUMBS', 'CRUNCH',
  'CRUSH', 'CRUST', 'CRUSTS', 'CRUX', 'CRY', 'CRYING', 'CRYPT', 'CRYSTAL', 'CUB', 'CUBE', 'CUBIC', 'CUBS',
  'CUDDLE', 'CUE', 'CUED', 'CUES', 'CUFF', 'CUISINE', 'CULT', 'CULTURE', 'CUMIN', 'CUP', 'CUPS', 'CUR',
  'CURATE', 'CURB', 'CURD', 'CURE', 'CURIO', 'CURIOUS', 'CURL', 'CURLY', 'CURRENT', 'CURRY', 'CURSE', 'CURSED',
  'CURT', 'CURTAIN', 'CURVE', 'CURVES', 'CURVY', 'CUSP', 'CUSTODY', 'CUSTOM', 'CUSTOMS', 'CUT', 'CUTE', 'CUTS',
  'CUTTER', 'CUTTING', 'CYCLE', 'CYCLES', 'CYMBAL', 'CYNIC', 'CYST', 'DAB', 'DAD', 'DADDY', 'DAILY', 'DAIRY',
  'DAIS', 'DAISY', 'DALE', 'DALLY', 'DAM', 'DAMAGE', 'DAMAGED', 'DAMAGES', 'DAMP', 'DAMS', 'DANCE', 'DANCER',
  'DANCERS', 'DANCES', 'DANCING', 'DANDY', 'DANGER', 'DANGERS', 'DANGLED', 'DANK', 'DARE', 'DARING', 'DARK', 'DARKER',
  'DART', 'DARTED', 'DARTING', 'DASH', 'DASHED', 'DATA', 'DATE', 'DATING', 'DATUM', 'DAUNT', 'DAWN', 'DAY',
  'DAYS', 'DAZE', 'DAZZLE', 'DEAD', 'DEADLY', 'DEAF', 'DEAFEN', 'DEAL', 'DEALER', 'DEALT', 'DEAN', 'DEAR',
  'DEARER', 'DEARLY', 'DEATH', 'DEBAR', 'DEBATE', 'DEBATED', 'DEBIT', 'DEBRIS', 'DEBT', 'DEBTOR', 'DEBUG', 'DEBUT',
  'DECADE', 'DECAL', 'DECANT', 'DECAY', 'DECEIT', 'DECIDE', 'DECIDED', 'DECIDES', 'DECK', 'DECLARE', 'DECLINE', 'DECODE',
  'DECOR', 'DECOY', 'DECREE', 'DECREED', 'DECRY', 'DEDUCE', 'DEED', 'DEEM', 'DEEP', 'DEER', 'DEFAULT', 'DEFEAT',
  'DEFEATS', 'DEFECT', 'DEFEND', 'DEFENSE', 'DEFER', 'DEFICIT', 'DEFINE', 'DEFINED', 'DEFRAY', 'DEFT', 'DEFTLY', 'DEFY',
  'DEGREE', 'DEIGN', 'DEITY', 'DELAY', 'DELAYS', 'DELETE', 'DELIVER', 'DELL', 'DELTA', 'DELUDE', 'DELUGE', 'DELVE',
  'DEMAND', 'DEMANDS', 'DEMISE', 'DEMO', 'DEMON', 'DEMUR', 'DEN', 'DENIAL', 'DENIED', 'DENIM', 'DENOTE', 'DENSE',
  'DENSITY', 'DENT', 'DENTAL', 'DENY', 'DEPART', 'DEPEND', 'DEPICT', 'DEPLOY', 'DEPORT', 'DEPOSE', 'DEPOSIT', 'DEPOT',
  'DEPTH', 'DEPTHS', 'DEPUTY', 'DERBY', 'DERIDE', 'DERIVE', 'DERIVED', 'DESERT', 'DESERTS', 'DESERVE', 'DESIGN', 'DESIGNS',
  'DESIRE', 'DESIRED', 'DESK', 'DESPAIR', 'DESTROY', 'DETAIL', 'DETAILS', 'DETAIN', 'DETECT', 'DETECTS', 'DETER', 'DETEST',
  'DETOUR', 'DETOX', 'DEUCE', 'DEVELOP', 'DEVICE', 'DEVICES', 'DEVIL', 'DEVISE', 'DEVOID', 'DEVOTE', 'DEVOTED', 'DEVOUR',
  'DEVOUT', 'DEW', 'DIABET', 'DIAL', 'DIALECT', 'DIALOG', 'DIAMOND', 'DIAPER', 'DIARIES', 'DIARY', 'DICE', 'DICEY',
  'DID', 'DIE', 'DIED', 'DIES', 'DIET', 'DIFFER', 'DIG', 'DIGEST', 'DIGGER', 'DIGGING', 'DIGIT', 'DIGNITY',
  'DIGS', 'DIKE', 'DILEMMA', 'DILUTE', 'DILUTED', 'DIM', 'DIME', 'DIMMER', 'DIMPLE', 'DIMS', 'DIN', 'DINE',
  'DINER', 'DING', 'DINGO', 'DINGY', 'DINING', 'DINNER', 'DINNERS', 'DINT', 'DIP', 'DIPS', 'DIRE', 'DIRECT',
  'DIRECTS', 'DIRGE', 'DIRT', 'DIRTY', 'DISABLE', 'DISARM', 'DISBAR', 'DISC', 'DISCO', 'DISCUS', 'DISCUSS', 'DISEASE',
  'DISGUST', 'DISH', 'DISK', 'DISLIKE', 'DISMAY', 'DISMISS', 'DISOWN', 'DISPEL', 'DISPUT', 'DISPUTE', 'DISTAL', 'DISTANT',
  'DISTIL', 'DISTORT', 'DISTURB', 'DITCH', 'DITTO', 'DITTY', 'DIVE', 'DIVER', 'DIVERSE', 'DIVERT', 'DIVIDE', 'DIVIDED',
  'DIVIDES', 'DIVINE', 'DIZZY', 'DOCK', 'DOCS', 'DOCTOR', 'DOCTORS', 'DODGE', 'DODGY', 'DOE', 'DOER', 'DOES',
  'DOG', 'DOGMA', 'DOGS', 'DOING', 'DOLE', 'DOLL', 'DOLLAR', 'DOLLY', 'DOLPHIN', 'DOMAIN', 'DOMAINS', 'DOME',
  'DOMINO', 'DON', 'DONATE', 'DONATED', 'DONE', 'DONKEY', 'DONOR', 'DONUT', 'DOODLE', 'DOOM', 'DOOMED', 'DOOR',
  'DOORWAY', 'DOPE', 'DOPEY', 'DORK', 'DORM', 'DOSAGE', 'DOSE', 'DOT', 'DOTE', 'DOTH', 'DOTS', 'DOUBLE',
  'DOUBLED', 'DOUBT', 'DOUBTED', 'DOUBTS', 'DOUGH', 'DOUR', 'DOVE', 'DOWDY', 'DOWEL', 'DOWN', 'DOWNY', 'DOWRY',
  'DOZE', 'DOZEN', 'DRAB', 'DRAFT', 'DRAG', 'DRAGON', 'DRAIN', 'DRAINED', 'DRAINS', 'DRAKE', 'DRAM', 'DRAMA',
  'DRANK', 'DRAPE', 'DRAW', 'DRAWER', 'DRAWERS', 'DRAWING', 'DRAWL', 'DRAWN', 'DRAY', 'DREAD', 'DREAM', 'DREAMY',
  'DRESS', 'DRESSED', 'DREW', 'DRIED', 'DRIER', 'DRIFT', 'DRIFTED', 'DRILL', 'DRILLS', 'DRINK', 'DRIP', 'DRIVE',
  'DRIVEN', 'DRIVER', 'DRIVERS', 'DRIVES', 'DRIVING', 'DROLL', 'DRONE', 'DRONES', 'DROOL', 'DROOP', 'DROP', 'DROPPED',
  'DROSS', 'DROVE', 'DROWN', 'DROWNS', 'DRUB', 'DRUG', 'DRUID', 'DRUM', 'DRUNK', 'DRY', 'DRYER', 'DRYLY',
  'DUAL', 'DUB', 'DUCHY', 'DUCK', 'DUCT', 'DUDE', 'DUE', 'DUEL', 'DUES', 'DUET', 'DUFF', 'DUG',
  'DUKE', 'DULL', 'DULLY', 'DULY', 'DUMB', 'DUMMY', 'DUMP', 'DUMPY', 'DUNCE', 'DUNE', 'DUNG', 'DURING',
  'DUSK', 'DUSKY', 'DUST', 'DUSTY', 'DUTCH', 'DUTIES', 'DUTY', 'DUVET', 'DWARF', 'DWELL', 'DWELT', 'DYAD',
  'DYE', 'DYED', 'DYES', 'DYING', 'DYNAMIC', 'EACH', 'EAGER', 'EAGLE', 'EAGLES', 'EAR', 'EARL', 'EARLIER',
  'EARLY', 'EARN', 'EARNED', 'EARNING', 'EARS', 'EARTH', 'EARTHEN', 'EARTHS', 'EASE', 'EASEL', 'EASIER', 'EASIEST',
  'EASILY', 'EAST', 'EASTERN', 'EASY', 'EAT', 'EATEN', 'EATER', 'EATING', 'EATS', 'EBB', 'EBONY', 'ECHO',
  'ECHOED', 'ECLAT', 'ECLIPSE', 'ECONOMY', 'EDDY', 'EDGE', 'EDGY', 'EDIBLE', 'EDICT', 'EDIFY', 'EDIT', 'EDITED',
  'EDITOR', 'EDUCATE', 'EEL', 'EERIE', 'EFFECT', 'EFFECTS', 'EFFORT', 'EFFORTS', 'EGG', 'EGGS', 'EGO', 'EGRET',
  'EIGHT', 'EIGHTH', 'EIRE', 'EITHER', 'EJECT', 'ELAPSE', 'ELAPSED', 'ELBOW', 'ELBOWS', 'ELDER', 'ELDERLY', 'ELDERS',
  'ELDEST', 'ELECT', 'ELECTS', 'ELEGANT', 'ELEGY', 'ELEMENT', 'ELEVATE', 'ELEVEN', 'ELF', 'ELFIN', 'ELICIT', 'ELIDE',
  'ELITE', 'ELK', 'ELM', 'ELOPE', 'ELSE', 'ELUDE', 'EMAIL', 'EMBALM', 'EMBARGO', 'EMBARK', 'EMBASSY', 'EMBED',
  'EMBER', 'EMBERS', 'EMBLEM', 'EMBODY', 'EMBRACE', 'EMCEE', 'EMERALD', 'EMERGE', 'EMERGED', 'EMERGES', 'EMIT', 'EMOTION',
  'EMPEROR', 'EMPIRE', 'EMPIRES', 'EMPLOY', 'EMPTY', 'EMUS', 'ENABLE', 'ENABLED', 'ENACT', 'ENACTED', 'ENACTS', 'ENAMEL',
  'ENCAMP', 'ENCASE', 'ENCORE', 'END', 'ENDEAR', 'ENDING', 'ENDLESS', 'ENDORSE', 'ENDOW', 'ENDOWS', 'ENDS', 'ENDURE',
  'ENDURED', 'ENEMA', 'ENEMIES', 'ENEMY', 'ENERGY', 'ENGAGE', 'ENGAGED', 'ENGINE', 'ENGINES', 'ENGULF', 'ENHANCE', 'ENIGMA',
  'ENJOY', 'ENJOYED', 'ENJOYS', 'ENLIST', 'ENMESH', 'ENMITY', 'ENNUI', 'ENOUGH', 'ENRAGE', 'ENRICH', 'ENROLL', 'ENSIGN',
  'ENSURE', 'ENSURED', 'ENTAIL', 'ENTER', 'ENTERED', 'ENTERS', 'ENTICE', 'ENTIRE', 'ENTITY', 'ENTOMB', 'ENTRAP', 'ENTREE',
  'ENTRY', 'ENVIED', 'ENVOY', 'ENVOYS', 'ENVY', 'EON', 'EONS', 'EPIC', 'EPILOG', 'EPISODE', 'EPOCH', 'EPOXY',
  'EQUAL', 'EQUALLY', 'EQUALS', 'EQUATE', 'EQUATOR', 'EQUIP', 'EQUITY', 'ERA', 'ERAS', 'ERASE', 'ERASED', 'ERASER',
  'ERECT', 'ERECTS', 'ERGO', 'ERODE', 'EROSION', 'ERRAND', 'ERRANT', 'ERROR', 'ERRORS', 'ERUPT', 'ERUPTS', 'ESCAPE',
  'ESCAPED', 'ESCAPES', 'ESCORT', 'ESCROW', 'ESSAY', 'ESSAYS', 'ESSENCE', 'ESTATE', 'ESTATES', 'ESTEEM', 'ESTER', 'ETERNAL',
  'ETHER', 'ETHIC', 'ETHICAL', 'ETHICS', 'ETHNIC', 'ETHOS', 'EULOGY', 'EVADE', 'EVADED', 'EVE', 'EVEN', 'EVENING',
  'EVENLY', 'EVENT', 'EVENTS', 'EVER', 'EVERY', 'EVICT', 'EVIDENT', 'EVIL', 'EVOKE', 'EVOLVE', 'EXACT', 'EXACTLY',
  'EXACTS', 'EXALT', 'EXALTS', 'EXAM', 'EXAMINE', 'EXAMPLE', 'EXCEED', 'EXCEEDS', 'EXCEL', 'EXCELS', 'EXCEPT', 'EXCESS',
  'EXCISE', 'EXCITE', 'EXCITED', 'EXCUSE', 'EXCUSES', 'EXEC', 'EXECUTE', 'EXEMPT', 'EXERT', 'EXERTS', 'EXES', 'EXHALE',
  'EXHAUST', 'EXHIBIT', 'EXILE', 'EXILED', 'EXIST', 'EXISTED', 'EXISTS', 'EXIT', 'EXODUS', 'EXPAND', 'EXPANDS', 'EXPECT',
  'EXPECTS', 'EXPEL', 'EXPENSE', 'EXPERT', 'EXPERTS', 'EXPIRE', 'EXPLAIN', 'EXPLORE', 'EXPO', 'EXPORT', 'EXPORTS', 'EXPOSE',
  'EXPOSED', 'EXPRESS', 'EXTEND', 'EXTENDS', 'EXTENT', 'EXTENTS', 'EXTOL', 'EXTORT', 'EXTRA', 'EXTREME', 'EXULT', 'EYE',
  'EYED', 'EYEING', 'EYELET', 'EYES', 'EYING', 'FABLE', 'FABRIC', 'FACADE', 'FACE', 'FACET', 'FACETS', 'FACIAL',
  'FACING', 'FACT', 'FACTOR', 'FACTORS', 'FACTORY', 'FACULTY', 'FAD', 'FADE', 'FADS', 'FAIL', 'FAILED', 'FAILING',
  'FAILURE', 'FAINT', 'FAIR', 'FAIRER', 'FAIRLY', 'FAIRWAY', 'FAIRY', 'FAITH', 'FAITHS', 'FAKE', 'FALCON', 'FALCONS',
  'FALL', 'FALLEN', 'FALLING', 'FALSE', 'FAME', 'FAMILY', 'FAMINE', 'FAMOUS', 'FAN', 'FANCY', 'FANG', 'FANNY',
  'FANS', 'FAR', 'FARCE', 'FARE', 'FARM', 'FARMER', 'FARMING', 'FASHION', 'FAST', 'FASTEN', 'FASTER', 'FASTEST',
  'FAT', 'FATAL', 'FATE', 'FATHER', 'FATHOM', 'FATIGUE', 'FATS', 'FATTY', 'FAULT', 'FAULTY', 'FAUNA', 'FAVOR',
  'FAVORS', 'FAWN', 'FAZE', 'FEAR', 'FEARED', 'FEAST', 'FEAT', 'FEATURE', 'FECAL', 'FED', 'FEDERAL', 'FEE',
  'FEEBLE', 'FEED', 'FEEDER', 'FEEDING', 'FEEL', 'FEELER', 'FEELING', 'FEES', 'FEET', 'FEIGN', 'FELINE', 'FELL',
  'FELLA', 'FELLOW', 'FELON', 'FELT', 'FEMALE', 'FEMME', 'FEMUR', 'FENCE', 'FEND', 'FENDER', 'FERAL', 'FERN',
  'FERRET', 'FERRY', 'FEST', 'FETAL', 'FETCH', 'FETID', 'FETTER', 'FEUD', 'FEVER', 'FEW', 'FEWER', 'FIANCE',
  'FIAT', 'FIBER', 'FIBERS', 'FICKLE', 'FICTION', 'FICUS', 'FIEF', 'FIELD', 'FIELDS', 'FIEND', 'FIERCE', 'FIERY',
  'FIESTA', 'FIFTEEN', 'FIFTH', 'FIFTHS', 'FIFTY', 'FIG', 'FIGHT', 'FIGHTER', 'FIGS', 'FIGURE', 'FIGURES', 'FILCH',
  'FILE', 'FILET', 'FILING', 'FILL', 'FILLED', 'FILLER', 'FILLING', 'FILLY', 'FILM', 'FILMY', 'FILTER', 'FILTERS',
  'FILTH', 'FILTHY', 'FIN', 'FINAL', 'FINALE', 'FINALS', 'FINANCE', 'FINCH', 'FIND', 'FINDER', 'FINDERS', 'FINDING',
  'FINE', 'FINELY', 'FINER', 'FINERY', 'FINESSE', 'FINGER', 'FINGERS', 'FINISH', 'FINK', 'FINS', 'FIR', 'FIRE',
  'FIREMAN', 'FIRING', 'FIRM', 'FIRMED', 'FIRMER', 'FIRS', 'FIRST', 'FIRSTS', 'FISCAL', 'FISH', 'FISHES', 'FISHY',
  'FIST', 'FIT', 'FITS', 'FITTED', 'FITTER', 'FITTING', 'FIVE', 'FIX', 'FIXER', 'FIXING', 'FIXS', 'FIXTURE',
  'FIZZLE', 'FIZZY', 'FJORD', 'FLACK', 'FLAG', 'FLAIL', 'FLAIR', 'FLAK', 'FLAKE', 'FLAKES', 'FLAKY', 'FLAM',
  'FLAME', 'FLAMES', 'FLAN', 'FLANGE', 'FLANK', 'FLANKS', 'FLANNEL', 'FLAP', 'FLARE', 'FLARED', 'FLARES', 'FLASH',
  'FLASHY', 'FLASK', 'FLASKS', 'FLAT', 'FLATLY', 'FLAUNT', 'FLAVOR', 'FLAVORS', 'FLAW', 'FLAWED', 'FLAX', 'FLEA',
  'FLECK', 'FLED', 'FLEE', 'FLEECE', 'FLEET', 'FLEETS', 'FLESH', 'FLEW', 'FLEX', 'FLICK', 'FLICKER', 'FLIER',
  'FLIGHT', 'FLIGHTS', 'FLINCH', 'FLING', 'FLINT', 'FLIP', 'FLIRT', 'FLIRTS', 'FLIT', 'FLOAT', 'FLOATED', 'FLOATS',
  'FLOC', 'FLOCK', 'FLOCKS', 'FLOG', 'FLOOD', 'FLOODS', 'FLOOR', 'FLOORS', 'FLOP', 'FLORA', 'FLORAL', 'FLOSS',
  'FLOUR', 'FLOUT', 'FLOW', 'FLOWER', 'FLOWERS', 'FLOWING', 'FLOWN', 'FLU', 'FLUB', 'FLUE', 'FLUENT', 'FLUFF',
  'FLUID', 'FLUIDS', 'FLUKE', 'FLUME', 'FLUNG', 'FLUNK', 'FLURRY', 'FLUSH', 'FLUTE', 'FLUTED', 'FLUTES', 'FLY',
  'FLYER', 'FLYERS', 'FLYING', 'FOAL', 'FOAM', 'FOAMY', 'FOCAL', 'FOCUS', 'FOCUSED', 'FOE', 'FOES', 'FOG',
  'FOGGY', 'FOIL', 'FOIST', 'FOLD', 'FOLDER', 'FOLIAGE', 'FOLIO', 'FOLK', 'FOLLOW', 'FOLLY', 'FOND', 'FONDLE',
  'FONDLY', 'FONT', 'FOOD', 'FOOL', 'FOOLED', 'FOOT', 'FOOTED', 'FOR', 'FORAGE', 'FORAY', 'FORBID', 'FORBIDS',
  'FORCE', 'FORCED', 'FORCES', 'FORCING', 'FORD', 'FORE', 'FOREIGN', 'FOREST', 'FORESTS', 'FOREVER', 'FORGE', 'FORGET',
  'FORGIVE', 'FORGO', 'FORGOT', 'FORK', 'FORM', 'FORMAL', 'FORMAT', 'FORMED', 'FORMER', 'FORMULA', 'FORT', 'FORTE',
  'FORTH', 'FORTUNE', 'FORTY', 'FORUM', 'FORWARD', 'FOSSIL', 'FOSTER', 'FOUGHT', 'FOUL', 'FOUND', 'FOUNDED', 'FOUNDER',
  'FOUNT', 'FOUR', 'FOURTH', 'FOURTHS', 'FOWL', 'FOX', 'FOXY', 'FOYER', 'FRAGILE', 'FRAIL', 'FRAME', 'FRAMED',
  'FRAMES', 'FRANCS', 'FRANK', 'FRAUD', 'FRAY', 'FREAK', 'FREAKS', 'FREE', 'FREED', 'FREEDOM', 'FREELY', 'FREER',
  'FREEZE', 'FREEZER', 'FRENCH', 'FRENZY', 'FRESH', 'FRET', 'FRIAR', 'FRIARS', 'FRIDAY', 'FRIDAYS', 'FRIED', 'FRIEND',
  'FRIENDS', 'FRIGHT', 'FRIGHTS', 'FRILL', 'FRINGE', 'FRISK', 'FRITZ', 'FROCK', 'FROCKS', 'FROG', 'FROLIC', 'FROM',
  'FROND', 'FRONT', 'FROST', 'FROSTED', 'FROTH', 'FROTHY', 'FROWN', 'FROZE', 'FROZEN', 'FRUGAL', 'FRUIT', 'FRUITS',
  'FRY', 'FUDGE', 'FUEL', 'FUGUE', 'FULFIL', 'FULFILL', 'FULL', 'FULLER', 'FULLY', 'FUMBLE', 'FUME', 'FUN',
  'FUND', 'FUNDED', 'FUNDING', 'FUNERAL', 'FUNGAL', 'FUNGI', 'FUNK', 'FUNKY', 'FUNNEL', 'FUNNY', 'FUR', 'FURL',
  'FURNACE', 'FUROR', 'FURROW', 'FURRY', 'FURS', 'FURTHER', 'FURY', 'FUSE', 'FUSION', 'FUSS', 'FUSSY', 'FUTURE',
  'FUTURES', 'FUZZ', 'FUZZY', 'GABS', 'GAFFE', 'GAG', 'GAGS', 'GAILY', 'GAIN', 'GAIT', 'GALA', 'GALAXY',
  'GALE', 'GALL', 'GALLERY', 'GALLEY', 'GALLON', 'GALLOP', 'GAMBLE', 'GAMBLER', 'GAME', 'GAMER', 'GAMING', 'GAMMA',
  'GAMUT', 'GANG', 'GAP', 'GAPS', 'GARAGE', 'GARAGES', 'GARB', 'GARBAGE', 'GARDEN', 'GARDENS', 'GARLIC', 'GARMENT',
  'GARNER', 'GARNET', 'GARTER', 'GAS', 'GASH', 'GASKET', 'GASP', 'GASSY', 'GATE', 'GATEWAY', 'GATHER', 'GAUDY',
  'GAUGE', 'GAUNT', 'GAUZE', 'GAVE', 'GAVEL', 'GAWKY', 'GAY', 'GAZE', 'GAZEBO', 'GEAR', 'GECKO', 'GEEK',
  'GEEKY', 'GEES', 'GEESE', 'GEL', 'GELATO', 'GELD', 'GEM', 'GEMS', 'GENDER', 'GENE', 'GENERAL', 'GENERIC',
  'GENETIC', 'GENIAL', 'GENIE', 'GENIUS', 'GENRE', 'GENT', 'GENTLE', 'GENTLY', 'GENUINE', 'GEODES', 'GERM', 'GERMAN',
  'GESTURE', 'GET', 'GETS', 'GEYSER', 'GHETTO', 'GHOST', 'GHOSTS', 'GHOUL', 'GIANT', 'GIANTS', 'GIDDY', 'GIFT',
  'GIFTED', 'GIGGLE', 'GILL', 'GILT', 'GIN', 'GINGER', 'GIRD', 'GIRDLE', 'GIRL', 'GIRTH', 'GIST', 'GIVE',
  'GIVEN', 'GIVER', 'GLACIER', 'GLAD', 'GLADE', 'GLADLY', 'GLAMOUR', 'GLANCE', 'GLANCES', 'GLAND', 'GLANDS', 'GLARE',
  'GLARES', 'GLASS', 'GLASSY', 'GLAZE', 'GLEAM', 'GLEAN', 'GLEE', 'GLEN', 'GLIB', 'GLIDE', 'GLIDER', 'GLIMMER',
  'GLIMPSE', 'GLINT', 'GLOAT', 'GLOBAL', 'GLOBE', 'GLOBES', 'GLOOM', 'GLOOMY', 'GLORY', 'GLOSS', 'GLOVE', 'GLOVES',
  'GLOW', 'GLOWED', 'GLUE', 'GLUM', 'GLUT', 'GLYPH', 'GNASH', 'GNAT', 'GNAW', 'GNOME', 'GNU', 'GOAD',
  'GOAL', 'GOAT', 'GOB', 'GOBLIN', 'GOD', 'GODDESS', 'GODLY', 'GODS', 'GOES', 'GOING', 'GOLD', 'GOLDEN',
  'GOLEM', 'GOLF', 'GOLFER', 'GONE', 'GONER', 'GONG', 'GOO', 'GOOD', 'GOODY', 'GOOEY', 'GOOF', 'GOOFY',
  'GOOSE', 'GORE', 'GORGE', 'GORILLA', 'GORY', 'GOSH', 'GOSPEL', 'GOSSIP', 'GOT', 'GOUGE', 'GOURD', 'GOUT',
  'GOVERN', 'GOVERNS', 'GOWN', 'GRAB', 'GRACE', 'GRACES', 'GRAD', 'GRADE', 'GRADED', 'GRADER', 'GRADES', 'GRADUAL',
  'GRAFT', 'GRAFTS', 'GRAIL', 'GRAIN', 'GRAINED', 'GRAINS', 'GRAM', 'GRAMMAR', 'GRAN', 'GRAND', 'GRANGE', 'GRANITE',
  'GRANT', 'GRANTS', 'GRAPE', 'GRAPES', 'GRAPH', 'GRAPHIC', 'GRAPHS', 'GRASP', 'GRASS', 'GRASSY', 'GRATE', 'GRATED',
  'GRATER', 'GRAVE', 'GRAVEL', 'GRAVES', 'GRAVITY', 'GRAVY', 'GRAY', 'GRAZE', 'GRAZED', 'GREASE', 'GREAT', 'GREATER',
  'GREED', 'GREEDY', 'GREEKS', 'GREEN', 'GREENS', 'GREET', 'GREETED', 'GREETS', 'GREW', 'GREY', 'GRID', 'GRIEF',
  'GRIEFS', 'GRIEVE', 'GRILL', 'GRILLS', 'GRIM', 'GRIME', 'GRIMLY', 'GRIMY', 'GRIN', 'GRIND', 'GRINDS', 'GRIP',
  'GRIPE', 'GRIPES', 'GRIT', 'GROAN', 'GROCER', 'GROCERY', 'GROG', 'GROIN', 'GROOM', 'GROOVE', 'GROPE', 'GROSS',
  'GROTTO', 'GROUND', 'GROUNDS', 'GROUP', 'GROUPS', 'GROUT', 'GROVE', 'GROW', 'GROWING', 'GROWL', 'GROWN', 'GROWTH',
  'GRUB', 'GRUDGE', 'GRUEL', 'GRUFF', 'GRUNT', 'GRUNTS', 'GUARD', 'GUARDED', 'GUARDS', 'GUAVA', 'GUESS', 'GUEST',
  'GUESTS', 'GUIDE', 'GUIDED', 'GUIDES', 'GUIDING', 'GUILD', 'GUILDS', 'GUILE', 'GUILT', 'GUILTY', 'GUISE', 'GUITAR',
  'GUITARS', 'GULF', 'GULL', 'GULLET', 'GULLY', 'GULP', 'GUM', 'GUMBO', 'GUMMY', 'GUMS', 'GUN', 'GUNS',
  'GUPPY', 'GURU', 'GUSH', 'GUST', 'GUSTO', 'GUSTY', 'GUT', 'GUTS', 'GUTTER', 'GUTTERS', 'GUY', 'GUYS',
  'GYM', 'GYMS', 'GYPSUM', 'GYPSY', 'GYRO', 'HABIT', 'HABITAT', 'HABITS', 'HACK', 'HACKER', 'HAD', 'HAGGLE',
  'HAIL', 'HAIR', 'HAIRY', 'HALE', 'HALF', 'HALL', 'HALO', 'HALT', 'HALVE', 'HALVES', 'HAM', 'HAMLET',
  'HAMMER', 'HAMMERS', 'HAND', 'HANDFUL', 'HANDLE', 'HANDLED', 'HANDLES', 'HANDY', 'HANG', 'HANGAR', 'HANGER', 'HANGING',
  'HANK', 'HAPPEN', 'HAPPENS', 'HAPPY', 'HARBOR', 'HARBORS', 'HARD', 'HARDEN', 'HARDER', 'HARDEST', 'HARDLY', 'HARDY',
  'HARE', 'HAREM', 'HARK', 'HARM', 'HARMONY', 'HARP', 'HARPY', 'HARROW', 'HARRY', 'HARSH', 'HART', 'HARVEST',
  'HAS', 'HASH', 'HASP', 'HAST', 'HASTE', 'HASTY', 'HAT', 'HATCH', 'HATE', 'HATER', 'HATH', 'HATS',
  'HAUL', 'HAUNT', 'HAUNTED', 'HAUTE', 'HAVE', 'HAVEN', 'HAVOC', 'HAWK', 'HAY', 'HAZARD', 'HAZE', 'HAZEL',
  'HAZY', 'HEAD', 'HEADED', 'HEADER', 'HEADING', 'HEADY', 'HEAL', 'HEALED', 'HEALER', 'HEALING', 'HEALTH', 'HEALTHY',
  'HEAP', 'HEAPED', 'HEAR', 'HEARD', 'HEARING', 'HEART', 'HEARTED', 'HEARTH', 'HEARTS', 'HEAT', 'HEATED', 'HEATER',
  'HEATERS', 'HEATH', 'HEATING', 'HEAVE', 'HEAVEN', 'HEAVENS', 'HEAVIER', 'HEAVILY', 'HEAVY', 'HECK', 'HEDGE', 'HEDGES',
  'HEED', 'HEEDED', 'HEEL', 'HEFT', 'HEFTY', 'HEIGHT', 'HEIGHTS', 'HEIR', 'HEIST', 'HELD', 'HELIX', 'HELLO',
  'HELM', 'HELMET', 'HELP', 'HELPED', 'HELPER', 'HELPFUL', 'HELPING', 'HEM', 'HEMP', 'HEN', 'HENCE', 'HENS',
  'HER', 'HERALD', 'HERB', 'HERBAL', 'HERD', 'HERE', 'HERMIT', 'HERO', 'HEROIC', 'HEROIN', 'HEROINE', 'HERON',
  'HERS', 'HEX', 'HEY', 'HID', 'HIDDEN', 'HIDE', 'HIGH', 'HIGHER', 'HIGHLY', 'HIGHWAY', 'HIKE', 'HIKING',
  'HILL', 'HILLY', 'HILT', 'HIM', 'HIND', 'HINDER', 'HINGE', 'HINGES', 'HINT', 'HINTED', 'HINTING', 'HIP',
  'HIPPO', 'HIPPY', 'HIPS', 'HIRE', 'HIRING', 'HIS', 'HISS', 'HISSES', 'HISTORY', 'HIT', 'HITCH', 'HITHER',
  'HITS', 'HIVE', 'HOARD', 'HOARSE', 'HOAX', 'HOB', 'HOBBY', 'HOBS', 'HOCK', 'HOCKEY', 'HOD', 'HOES',
  'HOG', 'HOGS', 'HOIST', 'HOLD', 'HOLDER', 'HOLDERS', 'HOLDING', 'HOLE', 'HOLLOW', 'HOLLOWS', 'HOLLY', 'HOLY',
  'HOME', 'HOMELY', 'HOMER', 'HONE', 'HONEST', 'HONESTY', 'HONEY', 'HONOR', 'HONORED', 'HONORS', 'HOOD', 'HOODED',
  'HOOF', 'HOOK', 'HOOKED', 'HOOP', 'HOOT', 'HOOTED', 'HOP', 'HOPE', 'HOPING', 'HOPS', 'HORDE', 'HORIZON',
  'HORN', 'HORNY', 'HORROR', 'HORRORS', 'HORSE', 'HORSES', 'HOSE', 'HOST', 'HOSTAGE', 'HOSTEL', 'HOSTILE', 'HOT',
  'HOTEL', 'HOTELS', 'HOTS', 'HOUND', 'HOUNDS', 'HOUR', 'HOURLY', 'HOUSE', 'HOUSES', 'HOUSING', 'HOVE', 'HOVEL',
  'HOVER', 'HOW', 'HOWDY', 'HOWEVER', 'HOWL', 'HOWLER', 'HOWS', 'HUB', 'HUBS', 'HUDDLE', 'HUE', 'HUES',
  'HUFF', 'HUG', 'HUGE', 'HUGS', 'HULA', 'HULK', 'HULL', 'HUM', 'HUMAN', 'HUMANE', 'HUMBLE', 'HUMBLY',
  'HUMID', 'HUMOR', 'HUMPH', 'HUMS', 'HUMUS', 'HUNCH', 'HUNDRED', 'HUNG', 'HUNGER', 'HUNGRY', 'HUNK', 'HUNKY',
  'HUNT', 'HUNTER', 'HUNTERS', 'HUNTING', 'HURDLE', 'HURL', 'HURLED', 'HURRY', 'HURT', 'HUSBAND', 'HUSH', 'HUSK',
  'HUSKY', 'HUSSY', 'HUSTLE', 'HUT', 'HUTCH', 'HUTS', 'HYBRID', 'HYDRO', 'HYENA', 'HYGIENE', 'HYMN', 'HYPE',
  'HYPER', 'HYPHEN', 'HYPO', 'IBIS', 'ICE', 'ICEBERG', 'ICED', 'ICES', 'ICICLE', 'ICING', 'ICON', 'ICY',
  'IDEA', 'IDEAL', 'IDEALS', 'IDIOM', 'IDIOT', 'IDLE', 'IDLER', 'IDLY', 'IDOL', 'IGLOO', 'IGNORE', 'ILL',
  'ILLNESS', 'IMAGE', 'IMAGES', 'IMAGINE', 'IMAGING', 'IMBUE', 'IMMENSE', 'IMMUNE', 'IMPACT', 'IMPACTS', 'IMPAIR', 'IMPART',
  'IMPASSE', 'IMPEL', 'IMPLY', 'IMPORT', 'IMPORTS', 'IMPOSE', 'IMPOSED', 'IMPRESS', 'IMPROVE', 'IMPULSE', 'IMPURE', 'INANE',
  'INBORN', 'INBOUND', 'INBOX', 'INBRED', 'INCENSE', 'INCH', 'INCHES', 'INCHING', 'INCITE', 'INCLUDE', 'INCOME', 'INCOMES',
  'INCUR', 'INDEED', 'INDENT', 'INDEX', 'INDEXES', 'INDIAN', 'INDIANS', 'INDICT', 'INDIGO', 'INDOOR', 'INDOORS', 'INDUCE',
  'INDUCED', 'INDUCT', 'INEPT', 'INERT', 'INFANCY', 'INFANT', 'INFANTS', 'INFECT', 'INFER', 'INFEST', 'INFIRM', 'INFO',
  'INFORM', 'INFORMS', 'INFUSE', 'INGOT', 'INHABIT', 'INHALE', 'INHERIT', 'INITIAL', 'INJECT', 'INJURE', 'INJURED', 'INJURY',
  'INK', 'INKLING', 'INKS', 'INKY', 'INLAID', 'INLAND', 'INLAY', 'INLET', 'INLETS', 'INMATE', 'INMATES', 'INMOST',
  'INN', 'INNATE', 'INNER', 'INNING', 'INNS', 'INPUT', 'INQUIRE', 'INQUIRY', 'INSANE', 'INSECT', 'INSERT', 'INSIDE',
  'INSIGHT', 'INSIST', 'INSISTS', 'INSOLE', 'INSPIRE', 'INSTALL', 'INSTANT', 'INSTEAD', 'INSTEP', 'INSULAR', 'INSULT', 'INSULTS',
  'INSURE', 'INSURED', 'INTACT', 'INTAKE', 'INTEGER', 'INTEND', 'INTENDS', 'INTENSE', 'INTENT', 'INTENTS', 'INTER', 'INTERIM',
  'INTERN', 'INTO', 'INTONE', 'INTRO', 'INTRUDE', 'INVADE', 'INVADED', 'INVADER', 'INVENT', 'INVERSE', 'INVEST', 'INVESTS',
  'INVITE', 'INVITED', 'INVITES', 'INVOKE', 'INVOLVE', 'INWARD', 'IODINE', 'ION', 'IONIC', 'IONS', 'IOTA', 'IRATE',
  'IRE', 'IRIS', 'IRKS', 'IRON', 'IRONED', 'IRONIC', 'IRONING', 'IRONY', 'ISLAND', 'ISLANDS', 'ISLE', 'ISLET',
  'ISLETS', 'ISOLATE', 'ISSUE', 'ISSUED', 'ISSUES', 'ISSUING', 'ITALIAN', 'ITALIC', 'ITCH', 'ITCHY', 'ITEM', 'ITSELF',
  'IVORY', 'IVY', 'JAB', 'JABS', 'JACK', 'JACKET', 'JACKETS', 'JADE', 'JAGGED', 'JAGUAR', 'JAIL', 'JAM',
  'JAMS', 'JANITOR', 'JAR', 'JARGON', 'JARS', 'JAUNT', 'JAUNTY', 'JAW', 'JAWS', 'JAY', 'JAYS', 'JAZZ',
  'JAZZY', 'JEALOUS', 'JEAN', 'JEEP', 'JEER', 'JELLY', 'JERKY', 'JERSEY', 'JEST', 'JESTER', 'JET', 'JETS',
  'JETTY', 'JEWEL', 'JEWELRY', 'JEWELS', 'JIBE', 'JIFFY', 'JIG', 'JIGS', 'JILT', 'JINX', 'JIVE', 'JOB',
  'JOBS', 'JOCK', 'JOCKEY', 'JOG', 'JOGGER', 'JOGS', 'JOIN', 'JOINED', 'JOINER', 'JOINT', 'JOINTS', 'JOKE',
  'JOKER', 'JOLLY', 'JOLT', 'JOLTED', 'JORDAN', 'JOSH', 'JOSTLE', 'JOT', 'JOTS', 'JOUR', 'JOURNEY', 'JOUST',
  'JOY', 'JOYFUL', 'JUBILEE', 'JUDGE', 'JUDGED', 'JUDGES', 'JUDGING', 'JUDO', 'JUG', 'JUGGLER', 'JUGS', 'JUICE',
  'JUICES', 'JUICY', 'JUMBLE', 'JUMBO', 'JUMP', 'JUMPED', 'JUMPER', 'JUMPY', 'JUNE', 'JUNGLE', 'JUNIOR', 'JUNIORS',
  'JUNK', 'JUNTO', 'JURIES', 'JUROR', 'JURORS', 'JURY', 'JUST', 'JUSTICE', 'JUSTIFY', 'JUSTLY', 'JUT', 'JUTE',
  'KALE', 'KAPPA', 'KARMA', 'KAYAK', 'KEBAB', 'KEEL', 'KEEN', 'KEEP', 'KEEPER', 'KEEPERS', 'KEEPING', 'KEG',
  'KEGS', 'KELP', 'KENNEL', 'KEPT', 'KERNEL', 'KETTLE', 'KEY', 'KEYHOLE', 'KEYS', 'KHAKI', 'KICK', 'KICKED',
  'KICKER', 'KICKING', 'KID', 'KIDNAP', 'KIDNAPS', 'KIDNEY', 'KIDNEYS', 'KIDS', 'KILL', 'KILLED', 'KILLER', 'KILLING',
  'KILN', 'KILO', 'KILT', 'KIN', 'KIND', 'KINDLE', 'KINDLY', 'KINDRED', 'KING', 'KINGDOM', 'KINGLY', 'KINK',
  'KIOSK', 'KISS', 'KISSES', 'KISSING', 'KIT', 'KITCHEN', 'KITE', 'KITS', 'KITTEN', 'KITTY', 'KNACK', 'KNAVE',
  'KNEAD', 'KNEE', 'KNEED', 'KNEEL', 'KNELL', 'KNELT', 'KNEW', 'KNIFE', 'KNIGHT', 'KNIGHTS', 'KNIT', 'KNIVES',
  'KNOB', 'KNOCK', 'KNOCKS', 'KNOLL', 'KNOT', 'KNOW', 'KNOWING', 'KNOWN', 'KOALA', 'KRILL', 'LAB', 'LABEL',
  'LABELED', 'LABELS', 'LABOR', 'LABORS', 'LABS', 'LACE', 'LACK', 'LACY', 'LAD', 'LADDER', 'LADEN', 'LADIES',
  'LADLE', 'LADS', 'LADY', 'LAG', 'LAGER', 'LAGOON', 'LAID', 'LAIR', 'LAKE', 'LAM', 'LAMB', 'LAME',
  'LAMENT', 'LAMP', 'LAMS', 'LANCE', 'LANCER', 'LANCES', 'LAND', 'LANDED', 'LANDING', 'LANE', 'LANK', 'LANKY',
  'LANTERN', 'LAP', 'LAPEL', 'LAPS', 'LAPSE', 'LAPTOP', 'LARD', 'LARDER', 'LARGE', 'LARGELY', 'LARGER', 'LARGEST',
  'LARK', 'LARVA', 'LASER', 'LASERS', 'LASH', 'LASHED', 'LASS', 'LASSO', 'LAST', 'LASTED', 'LASTING', 'LASTLY',
  'LATCH', 'LATE', 'LATELY', 'LATENT', 'LATER', 'LATERAL', 'LATEST', 'LATH', 'LATHE', 'LATTE', 'LATTER', 'LAUD',
  'LAUGH', 'LAUGHED', 'LAUNCH', 'LAUNDRY', 'LAUREL', 'LAVA', 'LAVISH', 'LAW', 'LAWFUL', 'LAWN', 'LAWS', 'LAWSUIT',
  'LAWYER', 'LAWYERS', 'LAY', 'LAYER', 'LAYERS', 'LAYING', 'LAYOUT', 'LAYS', 'LAZILY', 'LAZY', 'LEACH', 'LEAD',
  'LEADER', 'LEADERS', 'LEADING', 'LEAF', 'LEAFLET', 'LEAFY', 'LEAGUE', 'LEAGUES', 'LEAK', 'LEAKY', 'LEAN', 'LEANED',
  'LEANT', 'LEAP', 'LEAPED', 'LEAPT', 'LEAR', 'LEARN', 'LEARNED', 'LEAS', 'LEASE', 'LEASED', 'LEASH', 'LEAST',
  'LEATHER', 'LEAVE', 'LEAVES', 'LECTURE', 'LED', 'LEDGE', 'LEECH', 'LEEK', 'LEER', 'LEERY', 'LEFT', 'LEFTY',
  'LEG', 'LEGACY', 'LEGAL', 'LEGALLY', 'LEGEND', 'LEGENDS', 'LEGGY', 'LEGION', 'LEGS', 'LEISURE', 'LEMON', 'LEMONS',
  'LEMUR', 'LEND', 'LENDER', 'LENDERS', 'LENDING', 'LENGTH', 'LENS', 'LENSES', 'LENT', 'LEOPARD', 'LEPER', 'LESS',
  'LESSER', 'LESSON', 'LESSONS', 'LEST', 'LET', 'LETHAL', 'LETS', 'LETTER', 'LETTERS', 'LETTUCE', 'LEVEL', 'LEVELS',
  'LEVER', 'LEVERS', 'LEVY', 'LEWD', 'LIABLE', 'LIAR', 'LIBEL', 'LIBERAL', 'LIBERTY', 'LIBRARY', 'LICE', 'LICENSE',
  'LICK', 'LICKED', 'LID', 'LIDS', 'LIE', 'LIED', 'LIEGE', 'LIEN', 'LIES', 'LIEU', 'LIFE', 'LIFT',
  'LIFTED', 'LIFTER', 'LIGHT', 'LIGHTED', 'LIGHTER', 'LIGHTLY', 'LIGHTS', 'LIKE', 'LIKELY', 'LIKEN', 'LILAC', 'LIMB',
  'LIMBO', 'LIME', 'LIMIT', 'LIMITED', 'LIMITS', 'LIMP', 'LINE', 'LINEAGE', 'LINEAR', 'LINEN', 'LINER', 'LINERS',
  'LINEUP', 'LINGER', 'LINGO', 'LINING', 'LININGS', 'LINK', 'LINKED', 'LINKING', 'LINT', 'LION', 'LIP', 'LIPID',
  'LIPS', 'LIQUID', 'LIQUIDS', 'LIQUOR', 'LISP', 'LIST', 'LISTEN', 'LISTING', 'LIT', 'LITE', 'LITERAL', 'LITHE',
  'LITTER', 'LITTLE', 'LIVE', 'LIVELY', 'LIVER', 'LIVID', 'LIVING', 'LIZARD', 'LLAMA', 'LOAD', 'LOADED', 'LOADER',
  'LOAF', 'LOAM', 'LOAMY', 'LOAN', 'LOATH', 'LOATHE', 'LOB', 'LOBBY', 'LOBE', 'LOBS', 'LOBSTER', 'LOCAL',
  'LOCALE', 'LOCATE', 'LOCK', 'LOCKED', 'LOCKER', 'LOCKET', 'LOCUS', 'LODE', 'LODGE', 'LODGED', 'LODGER', 'LOFT',
  'LOFTY', 'LOG', 'LOGGED', 'LOGGER', 'LOGIC', 'LOGICAL', 'LOGIN', 'LOGS', 'LOIN', 'LONE', 'LONELY', 'LONG',
  'LONGER', 'LOOK', 'LOOKED', 'LOOKING', 'LOOM', 'LOON', 'LOOP', 'LOOPY', 'LOOSE', 'LOOSEN', 'LOOSER', 'LOOT',
  'LOP', 'LORD', 'LORE', 'LORRY', 'LOSE', 'LOSER', 'LOSERS', 'LOSING', 'LOSS', 'LOSSES', 'LOST', 'LOT',
  'LOTION', 'LOTS', 'LOTTERY', 'LOUD', 'LOUDLY', 'LOUNGE', 'LOUSE', 'LOUSY', 'LOVE', 'LOVELY', 'LOVER', 'LOVING',
  'LOW', 'LOWER', 'LOWLY', 'LOWS', 'LOYAL', 'LUCID', 'LUCK', 'LUCKY', 'LUG', 'LUGGAGE', 'LULL', 'LULLABY',
  'LUMBER', 'LUMEN', 'LUMP', 'LUMPY', 'LUNACY', 'LUNAR', 'LUNCH', 'LUNG', 'LUNGE', 'LUPUS', 'LURCH', 'LURE',
  'LURID', 'LURK', 'LUSH', 'LUST', 'LUSTY', 'LUTE', 'LUXURY', 'LYING', 'LYRE', 'LYRIC', 'LYRICS', 'MACAW',
  'MACE', 'MACH', 'MACHINE', 'MACHO', 'MACRO', 'MACS', 'MAD', 'MADAM', 'MADE', 'MADLY', 'MAFIA', 'MAGIC',
  'MAGICAL', 'MAGMA', 'MAGNET', 'MAGNETS', 'MAGNIFY', 'MAID', 'MAIDEN', 'MAIDENS', 'MAIL', 'MAILED', 'MAILING', 'MAIM',
  'MAIN', 'MAINLY', 'MAIZE', 'MAJESTY', 'MAJOR', 'MAKE', 'MAKER', 'MAKERS', 'MAKING', 'MALE', 'MALL', 'MALT',
  'MAMA', 'MAMBO', 'MAMMA', 'MAN', 'MANAGE', 'MANAGED', 'MANAGER', 'MANAGES', 'MANDATE', 'MANE', 'MANGA', 'MANGE',
  'MANGER', 'MANGO', 'MANGY', 'MANIA', 'MANIC', 'MANKIND', 'MANLY', 'MANNER', 'MANOR', 'MANSION', 'MANUAL', 'MANUALS',
  'MANY', 'MAP', 'MAPLE', 'MAPPED', 'MAPPING', 'MAPS', 'MARBLE', 'MARBLES', 'MARCH', 'MARE', 'MARGIN', 'MARGINS',
  'MARINE', 'MARINES', 'MARK', 'MARKER', 'MARKERS', 'MARKET', 'MARKETS', 'MARRIED', 'MARROW', 'MARRY', 'MARS', 'MARSH',
  'MARTIAL', 'MARVEL', 'MARVELS', 'MASCOT', 'MASCOTS', 'MASH', 'MASK', 'MASON', 'MASS', 'MASSAGE', 'MASSE', 'MASSES',
  'MASSIVE', 'MAST', 'MASTER', 'MASTERS', 'MAT', 'MATCH', 'MATCHED', 'MATCHES', 'MATE', 'MATEY', 'MATH', 'MATS',
  'MATTER', 'MATURE', 'MAUL', 'MAUVE', 'MAW', 'MAXIM', 'MAXIMUM', 'MAY', 'MAYBE', 'MAYOR', 'MAZE', 'MEAD',
  'MEADOW', 'MEADOWS', 'MEAL', 'MEALY', 'MEAN', 'MEANER', 'MEANING', 'MEANLY', 'MEANT', 'MEASURE', 'MEAT', 'MEATY',
  'MECCA', 'MEDAL', 'MEDDLE', 'MEDIA', 'MEDIC', 'MEDICAL', 'MEDIUM', 'MEDIUMS', 'MEDLEY', 'MEEK', 'MEET', 'MEETING',
  'MELLOW', 'MELODY', 'MELON', 'MELT', 'MELTED', 'MELTING', 'MEMBER', 'MEMBERS', 'MEMO', 'MEMOIRS', 'MEMORY', 'MEN',
  'MENACE', 'MEND', 'MENDED', 'MENTAL', 'MENTION', 'MENTOR', 'MENU', 'MEOW', 'MERCURY', 'MERCY', 'MERE', 'MERELY',
  'MERGE', 'MERGER', 'MERIT', 'MERRY', 'MESA', 'MESH', 'MESS', 'MESSAGE', 'MET', 'METAL', 'METALS', 'METEOR',
  'METER', 'METERS', 'METHOD', 'METHODS', 'METRIC', 'METRICS', 'METRO', 'MICE', 'MICRO', 'MID', 'MIDDLE', 'MIDGE',
  'MIDGET', 'MIDST', 'MIGHT', 'MIGHTY', 'MILD', 'MILDEW', 'MILDLY', 'MILE', 'MILK', 'MILKY', 'MILL', 'MILLER',
  'MILLION', 'MIME', 'MIMIC', 'MINCE', 'MIND', 'MINDED', 'MINE', 'MINER', 'MINERAL', 'MINI', 'MINIM', 'MINIMUM',
  'MINING', 'MINION', 'MINK', 'MINOR', 'MINORS', 'MINT', 'MINTED', 'MINTY', 'MINUS', 'MINUTE', 'MINUTES', 'MINX',
  'MIRACLE', 'MIRAGE', 'MIRE', 'MIRROR', 'MIRRORS', 'MIRTH', 'MIRY', 'MISER', 'MISERY', 'MISS', 'MISSED', 'MISSILE',
  'MISSION', 'MISSY', 'MIST', 'MISTAKE', 'MITE', 'MITT', 'MITTEN', 'MIX', 'MIXERS', 'MIXING', 'MIXTURE', 'MOAN',
  'MOAT', 'MOB', 'MOBILE', 'MOBILES', 'MOCHA', 'MOCK', 'MOCKED', 'MODAL', 'MODE', 'MODEL', 'MODELS', 'MODEM',
  'MODERN', 'MODERNS', 'MODEST', 'MODIFY', 'MODULAR', 'MODULE', 'MOGUL', 'MOIST', 'MOLAR', 'MOLDY', 'MOLE', 'MOLT',
  'MOLTEN', 'MOM', 'MOMENT', 'MOMENTS', 'MONARCH', 'MONEY', 'MONITOR', 'MONK', 'MONKEY', 'MONSTER', 'MONTH', 'MONTHLY',
  'MONTHS', 'MOO', 'MOOD', 'MOODY', 'MOON', 'MOOR', 'MOOSE', 'MOOT', 'MOP', 'MOPE', 'MORAL', 'MORALE',
  'MORALS', 'MORE', 'MORN', 'MORNING', 'MORON', 'MORPH', 'MORTAL', 'MORTALS', 'MORTAR', 'MOSAIC', 'MOSQUE', 'MOSS',
  'MOSSY', 'MOST', 'MOSTLY', 'MOTEL', 'MOTH', 'MOTHER', 'MOTHERS', 'MOTIF', 'MOTION', 'MOTIONS', 'MOTIVE', 'MOTIVES',
  'MOTOR', 'MOTORS', 'MOTTO', 'MOULT', 'MOUND', 'MOUNT', 'MOUNTED', 'MOUNTS', 'MOURN', 'MOURNED', 'MOUSE', 'MOUTH',
  'MOUTHS', 'MOVABLE', 'MOVE', 'MOVER', 'MOVIE', 'MOVING', 'MOW', 'MOWER', 'MOWN', 'MUCH', 'MUCK', 'MUCKY',
  'MUCUS', 'MUD', 'MUDDY', 'MUDS', 'MUFF', 'MUFFIN', 'MUG', 'MUGS', 'MULCH', 'MULE', 'MULL', 'MUM',
  'MUMBLE', 'MUMMY', 'MURAL', 'MURDER', 'MURKY', 'MUSCLE', 'MUSE', 'MUSEUM', 'MUSEUMS', 'MUSH', 'MUSHY', 'MUSIC',
  'MUSICAL', 'MUSK', 'MUSKET', 'MUSKY', 'MUST', 'MUSTER', 'MUSTY', 'MUTE', 'MUTT', 'MUTTER', 'MUTUAL', 'MUZZLE',
  'MYRRH', 'MYSELF', 'MYSTERY', 'MYSTIC', 'MYTH', 'NAB', 'NAG', 'NAIL', 'NAIVE', 'NAME', 'NAMELY', 'NANNY',
  'NAP', 'NAPE', 'NAPS', 'NARROW', 'NASAL', 'NASTY', 'NATAL', 'NATION', 'NATIONS', 'NATIVE', 'NATURAL', 'NATURE',
  'NAUGHT', 'NAVAL', 'NAVEL', 'NAVY', 'NAY', 'NEAR', 'NEARBY', 'NEARER', 'NEAREST', 'NEARLY', 'NEAT', 'NEATLY',
  'NECK', 'NEED', 'NEEDED', 'NEEDLE', 'NEEDLES', 'NEEDY', 'NEGATE', 'NEGLECT', 'NEIGH', 'NEITHER', 'NEON', 'NEPHEW',
  'NERD', 'NERDY', 'NERVE', 'NERVES', 'NERVOUS', 'NEST', 'NESTED', 'NET', 'NETS', 'NETTLE', 'NETWORK', 'NEURAL',
  'NEUTER', 'NEUTRAL', 'NEVER', 'NEW', 'NEWBORN', 'NEWER', 'NEWEST', 'NEWLY', 'NEWS', 'NEWT', 'NEXT', 'NIB',
  'NIBBLE', 'NICE', 'NICER', 'NICHE', 'NICK', 'NICKEL', 'NIECE', 'NIGHT', 'NIGHTLY', 'NIGHTS', 'NIL', 'NINE',
  'NINETY', 'NINTH', 'NIP', 'NIPPLE', 'NIPS', 'NOBLE', 'NOBLEST', 'NOBLY', 'NOBODY', 'NOD', 'NODDED', 'NODE',
  'NODS', 'NOEL', 'NOISE', 'NOISY', 'NOMAD', 'NOMINAL', 'NONE', 'NOOK', 'NOON', 'NOOSE', 'NOPE', 'NOR',
  'NORM', 'NORMAL', 'NORTH', 'NOSE', 'NOSEY', 'NOSY', 'NOT', 'NOTABLE', 'NOTABLY', 'NOTCH', 'NOTE', 'NOTED',
  'NOTHING', 'NOTICE', 'NOTICED', 'NOTICES', 'NOTIFY', 'NOTION', 'NOUN', 'NOURISH', 'NOVA', 'NOVEL', 'NOVELS', 'NOVELTY',
  'NOVICE', 'NOW', 'NOZZLE', 'NUCLEAR', 'NUCLEUS', 'NUDE', 'NUDGE', 'NUMB', 'NUMBERS', 'NUN', 'NUNS', 'NURSE',
  'NURSED', 'NURSERY', 'NURSES', 'NURSING', 'NUT', 'NUTMEG', 'NUTS', 'NUTTY', 'NYMPH', 'OAF', 'OAK', 'OAKS',
  'OAR', 'OARS', 'OASIS', 'OAT', 'OATH', 'OATS', 'OBESE', 'OBEY', 'OBJECT', 'OBJECTS', 'OBLIGE', 'OBLIGED',
  'OBSERVE', 'OBTAIN', 'OBVIOUS', 'OCCUPY', 'OCCUR', 'OCEAN', 'OCEANS', 'OCTAVE', 'OCTET', 'OCTOBER', 'ODD', 'ODDER',
  'ODDLY', 'ODDS', 'ODE', 'ODOR', 'OFF', 'OFFAL', 'OFFENSE', 'OFFER', 'OFFERED', 'OFFICER', 'OFFICES', 'OFFSET',
  'OFT', 'OFTEN', 'OGRE', 'OIL', 'OILS', 'OILY', 'OKAY', 'OKRA', 'OLD', 'OLDEN', 'OLDER', 'OLDS',
  'OLIVE', 'OLIVES', 'OMBRE', 'OMEGA', 'OMELET', 'OMEN', 'OMIT', 'ONCE', 'ONE', 'ONES', 'ONGOING', 'ONION',
  'ONLINE', 'ONLOOK', 'ONLY', 'ONSET', 'ONTO', 'ONUS', 'ONWARD', 'OOZE', 'OPAL', 'OPEN', 'OPENED', 'OPENER',
  'OPENING', 'OPENLY', 'OPERA', 'OPERATE', 'OPINE', 'OPINION', 'OPIUM', 'OPPOSE', 'OPPOSED', 'OPT', 'OPTIC', 'OPTICS',
  'OPTIMA', 'OPTIMAL', 'OPTION', 'OPTIONS', 'OPUS', 'ORAL', 'ORANGE', 'ORANGES', 'ORATOR', 'ORB', 'ORBIT', 'ORBITAL',
  'ORBITS', 'ORCHARD', 'ORCHID', 'ORCS', 'ORDER', 'ORDERED', 'ORDERS', 'ORE', 'ORGAN', 'ORGANIC', 'ORGANS', 'ORGY',
  'ORIGIN', 'ORIGINS', 'OTHER', 'OTTER', 'OUCH', 'OUGHT', 'OUNCE', 'OUR', 'OURS', 'OUST', 'OUT', 'OUTCOME',
  'OUTDO', 'OUTDOOR', 'OUTER', 'OUTFIT', 'OUTGO', 'OUTING', 'OUTLAW', 'OUTLET', 'OUTLINE', 'OUTLOOK', 'OUTPUT', 'OUTS',
  'OUTSET', 'OUTSIDE', 'OUTWIT', 'OVAL', 'OVARY', 'OVATE', 'OVEN', 'OVER', 'OVERALL', 'OVERDUE', 'OVERLAP', 'OVERT',
  'OVINE', 'OVOID', 'OWED', 'OWES', 'OWING', 'OWL', 'OWLS', 'OWN', 'OWNER', 'OWNS', 'OXEN', 'OXIDE',
  'OXYGEN', 'OYSTER', 'OZONE', 'PACE', 'PACIFY', 'PACK', 'PACKAGE', 'PACKED', 'PACKER', 'PACKET', 'PACKETS', 'PACKING',
  'PACT', 'PAD', 'PADDLE', 'PADDY', 'PADS', 'PAGAN', 'PAGE', 'PAGING', 'PAID', 'PAIL', 'PAIN', 'PAINED',
  'PAINFUL', 'PAINT', 'PAINTED', 'PAINTER', 'PAINTS', 'PAIR', 'PAIRED', 'PAIRING', 'PAL', 'PALACE', 'PALACES', 'PALATE',
  'PALE', 'PALER', 'PALL', 'PALM', 'PALS', 'PALSY', 'PAN', 'PANCAKE', 'PANE', 'PANEL', 'PANELS', 'PANG',
  'PANIC', 'PANICS', 'PANS', 'PANSY', 'PANT', 'PANTRY', 'PAPA', 'PAPACY', 'PAPAL', 'PAPER', 'PAPERS', 'PAR',
  'PARADE', 'PARADES', 'PARCEL', 'PARDON', 'PARENT', 'PARER', 'PARISH', 'PARK', 'PARKA', 'PARKED', 'PARKING', 'PARLOR',
  'PARLORS', 'PARROT', 'PARRY', 'PARSE', 'PARSON', 'PART', 'PARTED', 'PARTIAL', 'PARTIES', 'PARTLY', 'PARTNER', 'PARTY',
  'PASS', 'PASSAGE', 'PASSED', 'PASSES', 'PASSING', 'PASSION', 'PASSIVE', 'PAST', 'PASTA', 'PASTE', 'PASTED', 'PASTEL',
  'PASTOR', 'PASTORS', 'PASTURE', 'PASTY', 'PAT', 'PATCH', 'PATCHED', 'PATCHES', 'PATENT', 'PATENTS', 'PATH', 'PATHWAY',
  'PATIENT', 'PATIO', 'PATROL', 'PATROLS', 'PATRON', 'PATS', 'PATSY', 'PATTER', 'PATTERN', 'PATTY', 'PAUSE', 'PAVE',
  'PAVING', 'PAW', 'PAWN', 'PAWS', 'PAY', 'PAYABLE', 'PAYEE', 'PAYER', 'PAYING', 'PAYMENT', 'PAYOFF', 'PAYS',
  'PEA', 'PEACE', 'PEACH', 'PEAK', 'PEAL', 'PEANUT', 'PEANUTS', 'PEAR', 'PEARL', 'PEARLS', 'PEAS', 'PEASANT',
  'PEAT', 'PEBBLE', 'PECAN', 'PECK', 'PEDAL', 'PEEK', 'PEEL', 'PEELED', 'PEEP', 'PEER', 'PEERED', 'PEG',
  'PEGS', 'PELICAN', 'PELLET', 'PELT', 'PELVIS', 'PEN', 'PENAL', 'PENALTY', 'PENCE', 'PENCIL', 'PENDING', 'PENNE',
  'PENNY', 'PENS', 'PENSION', 'PENT', 'PEON', 'PEOPLE', 'PEOPLED', 'PEP', 'PEPPER', 'PER', 'PERCENT', 'PERCH',
  'PERFECT', 'PERFORM', 'PERFUME', 'PERHAPS', 'PERIL', 'PERIOD', 'PERIODS', 'PERISH', 'PERK', 'PERKY', 'PERM', 'PERMIT',
  'PERMITS', 'PERSIST', 'PERSON', 'PERSONS', 'PESKY', 'PEST', 'PESTER', 'PESTO', 'PET', 'PETAL', 'PETALS', 'PETROL',
  'PETS', 'PETTY', 'PEW', 'PHANTOM', 'PHASE', 'PHASED', 'PHASES', 'PHEW', 'PHOENIX', 'PHONE', 'PHONY', 'PHOTO',
  'PHRASE', 'PHRASES', 'PIANO', 'PICA', 'PICK', 'PICKED', 'PICKER', 'PICKLE', 'PICKUP', 'PICKY', 'PICNIC', 'PICTURE',
  'PIE', 'PIECE', 'PIED', 'PIER', 'PIERCE', 'PIERCED', 'PIES', 'PIETY', 'PIG', 'PIGEON', 'PIGGY', 'PIGLET',
  'PIGMENT', 'PIGS', 'PIKE', 'PILE', 'PILGRIM', 'PILL', 'PILLOW', 'PILOT', 'PIMP', 'PIN', 'PINCH', 'PINCHED',
  'PINE', 'PINEY', 'PING', 'PINK', 'PINKY', 'PINNED', 'PINT', 'PINTO', 'PION', 'PIONEER', 'PIP', 'PIPE',
  'PIPER', 'PIPERS', 'PIPING', 'PIPS', 'PIQUE', 'PIRATE', 'PIRATES', 'PISTOL', 'PISTON', 'PIT', 'PITCH', 'PITCHER',
  'PITH', 'PITHY', 'PITY', 'PIVOT', 'PIXEL', 'PIXIE', 'PIXY', 'PIZZA', 'PLACE', 'PLACED', 'PLACES', 'PLAGUE',
  'PLAID', 'PLAIN', 'PLAIT', 'PLAN', 'PLANAR', 'PLANE', 'PLANET', 'PLANK', 'PLANKS', 'PLANNED', 'PLANNER', 'PLANT',
  'PLANTS', 'PLAQUE', 'PLASMS', 'PLASTIC', 'PLASTS', 'PLAT', 'PLATE', 'PLATEAU', 'PLATES', 'PLAY', 'PLAYED', 'PLAYER',
  'PLAYERS', 'PLAYFUL', 'PLAYING', 'PLAZA', 'PLEA', 'PLEAD', 'PLEADED', 'PLEASE', 'PLEAT', 'PLED', 'PLEDGE', 'PLEDGED',
  'PLENTY', 'PLIANT', 'PLIED', 'PLIER', 'PLIERS', 'PLIGHT', 'PLOD', 'PLOT', 'PLOW', 'PLOWED', 'PLUCK', 'PLUG',
  'PLUM', 'PLUMB', 'PLUMBER', 'PLUMBS', 'PLUME', 'PLUMES', 'PLUMP', 'PLUNGE', 'PLUNK', 'PLURAL', 'PLUS', 'PLUSH',
  'PLY', 'POCK', 'POCKET', 'POCKETS', 'POD', 'PODIUM', 'POEM', 'POESY', 'POET', 'POETIC', 'POETRY', 'POINT',
  'POINTED', 'POINTER', 'POINTS', 'POISE', 'POISON', 'POISONS', 'POKE', 'POKER', 'POKY', 'POLAR', 'POLARIS', 'POLE',
  'POLICE', 'POLICED', 'POLICES', 'POLICY', 'POLISH', 'POLITE', 'POLITIC', 'POLKA', 'POLL', 'POLLEN', 'POLLUTE', 'POLO',
  'POLYGON', 'POLYP', 'POMP', 'POND', 'PONIES', 'PONY', 'POOCH', 'POODLE', 'POOF', 'POOL', 'POOP', 'POOR',
  'POORLY', 'POP', 'POPE', 'POPLAR', 'POPPED', 'POPPY', 'POPS', 'POPULAR', 'PORCH', 'PORE', 'PORK', 'PORN',
  'PORT', 'PORTAL', 'PORTER', 'PORTION', 'PORTLY', 'POSE', 'POSER', 'POSH', 'POSING', 'POSIT', 'POSSE', 'POSSESS',
  'POST', 'POSTAGE', 'POSTAL', 'POSTED', 'POSTER', 'POSTERS', 'POSY', 'POT', 'POTATO', 'POTENT', 'POTTER', 'POTTERY',
  'POUCH', 'POULTRY', 'POUNCE', 'POUND', 'POUNDS', 'POUR', 'POURED', 'POUT', 'POUTY', 'POVERTY', 'POWDER', 'POWDERS',
  'POWER', 'POWERS', 'PRAISE', 'PRAISED', 'PRAISES', 'PRANK', 'PRAWN', 'PRAY', 'PRAYED', 'PRAYER', 'PRAYING', 'PREACH',
  'PREDICT', 'PREEN', 'PREFACE', 'PREFER', 'PREFIX', 'PREMIER', 'PREP', 'PREPARE', 'PREPAY', 'PRESENT', 'PRESET', 'PRESS',
  'PRETTY', 'PREVENT', 'PREVIEW', 'PREY', 'PRICE', 'PRICED', 'PRICES', 'PRICEY', 'PRICK', 'PRIDE', 'PRIED', 'PRIEST',
  'PRIG', 'PRIM', 'PRIMAL', 'PRIMARY', 'PRIMATE', 'PRIME', 'PRIMER', 'PRIMO', 'PRINCE', 'PRINCES', 'PRINT', 'PRINTED',
  'PRINTER', 'PRINTS', 'PRIOR', 'PRIORS', 'PRISM', 'PRISON', 'PRIVACY', 'PRIVATE', 'PRIVY', 'PRIZE', 'PRIZED', 'PRIZES',
  'PRO', 'PROBE', 'PROBED', 'PROBES', 'PROBLEM', 'PROCEED', 'PROCESS', 'PROD', 'PRODUCE', 'PRODUCT', 'PROFILE', 'PROFIT',
  'PROFITS', 'PROGRAM', 'PROJECT', 'PROM', 'PROMISE', 'PROMPT', 'PRONE', 'PRONG', 'PRONGS', 'PROOF', 'PROOFS', 'PROP',
  'PROPER', 'PROPOS', 'PROPOSE', 'PROS', 'PROSE', 'PROTECT', 'PROTEST', 'PROUD', 'PROUDLY', 'PROVE', 'PROVED', 'PROVEN',
  'PROVERB', 'PROVES', 'PROVIDE', 'PROW', 'PROWL', 'PROWLS', 'PROXY', 'PRUDE', 'PRUNE', 'PRUNED', 'PRUNES', 'PRY',
  'PSALM', 'PUB', 'PUBIC', 'PUBLIC', 'PUBS', 'PUCK', 'PUDGY', 'PUFF', 'PUFFED', 'PUFFY', 'PUG', 'PUGS',
  'PULL', 'PULLED', 'PULLING', 'PULP', 'PULPIT', 'PULPY', 'PULSE', 'PULSED', 'PULSES', 'PUMA', 'PUMP', 'PUMPED',
  'PUMPING', 'PUN', 'PUNCH', 'PUNCHED', 'PUNISH', 'PUNK', 'PUNS', 'PUNT', 'PUNY', 'PUP', 'PUPA', 'PUPIL',
  'PUPILS', 'PUPPET', 'PUPPY', 'PUPS', 'PURE', 'PUREE', 'PURELY', 'PURER', 'PURGE', 'PURIFY', 'PURITY', 'PURL',
  'PURPLE', 'PURPOSE', 'PURR', 'PURSE', 'PURSUE', 'PURSUED', 'PURSUES', 'PURSUIT', 'PUS', 'PUSH', 'PUSHED', 'PUSHER',
  'PUSHES', 'PUSHY', 'PUSS', 'PUT', 'PUTS', 'PUTT', 'PUTTY', 'PUZZLE', 'PUZZLES', 'PYGMY', 'PYRAMID', 'PYRE',
  'QUACK', 'QUAD', 'QUAIL', 'QUAKE', 'QUALIFY', 'QUALITY', 'QUALM', 'QUARK', 'QUARREL', 'QUART', 'QUARTER', 'QUARTET',
  'QUASH', 'QUASI', 'QUAY', 'QUEEN', 'QUEER', 'QUELL', 'QUERIES', 'QUERY', 'QUEST', 'QUEUE', 'QUICK', 'QUICKER',
  'QUICKLY', 'QUIET', 'QUIETER', 'QUIETLY', 'QUILL', 'QUILT', 'QUIP', 'QUIRK', 'QUIT', 'QUITE', 'QUIZ', 'QUOTA',
  'QUOTE', 'QUOTH', 'RABBI', 'RABBITS', 'RABID', 'RACE', 'RACER', 'RACK', 'RACY', 'RADAR', 'RADIANT', 'RADICAL',
  'RADII', 'RADIO', 'RAFFLES', 'RAFT', 'RAG', 'RAGE', 'RAGS', 'RAID', 'RAIL', 'RAILWAY', 'RAIN', 'RAINBOW',
  'RAINY', 'RAISE', 'RAISING', 'RAJAH', 'RAKE', 'RALLY', 'RALPH', 'RAM', 'RAMEN', 'RAMP', 'RAMPART', 'RAMS',
  'RAN', 'RANCH', 'RANCHER', 'RANDY', 'RANG', 'RANGE', 'RANK', 'RANKING', 'RANT', 'RAP', 'RAPID', 'RAPIDLY',
  'RAPS', 'RAPT', 'RARE', 'RARER', 'RASH', 'RASP', 'RASPY', 'RAT', 'RATE', 'RATIO', 'RATS', 'RATTY',
  'RAVE', 'RAVEN', 'RAW', 'RAY', 'RAYON', 'RAYS', 'RAZE', 'RAZOR', 'REACH', 'REACHED', 'REACHES', 'REACT',
  'REACTED', 'REACTOR', 'READ', 'READERS', 'READILY', 'READING', 'READY', 'REAL', 'REALITY', 'REALIZE', 'REALM', 'REAM',
  'REAP', 'REAR', 'REARM', 'REASONS', 'REBAR', 'REBEL', 'REBOUND', 'REBUS', 'REBUT', 'RECAP', 'RECEIPT', 'RECEIVE',
  'RECIPES', 'RECK', 'RECLAIM', 'RECLINE', 'RECORDS', 'RECOVER', 'RECRUIT', 'RECUR', 'RECUT', 'RED', 'REDO', 'REDUCED',
  'REDUCES', 'REED', 'REEDY', 'REEF', 'REEK', 'REEL', 'REFER', 'REFINED', 'REFIT', 'REFLECT', 'REFORMS', 'REFRESH',
  'REFUGEE', 'REFUSAL', 'REFUSED', 'REGAL', 'REGARDS', 'REGATTA', 'REGIMES', 'REGIONS', 'REGULAR', 'REHAB', 'REIGN', 'REIN',
  'REJECTS', 'RELAPSE', 'RELATED', 'RELATES', 'RELAX', 'RELAY', 'RELIC', 'RELIEFS', 'RELIEVE', 'RELY', 'REMAINS', 'REMARKS',
  'REMIT', 'REMOVAL', 'REMOVED', 'REMOVES', 'RENAL', 'RENEW', 'RENT', 'REPAIRS', 'REPAY', 'REPEATS', 'REPEL', 'REPLACE',
  'REPLIED', 'REPLIES', 'REPLY', 'REPORTS', 'REQUEST', 'REQUIRE', 'RERUN', 'RESCUED', 'RESCUES', 'RESERVE', 'RESET', 'RESIDED',
  'RESIDES', 'RESIN', 'RESISTS', 'RESOLVE', 'RESORTS', 'RESPECT', 'RESPOND', 'REST', 'RESTING', 'RESTORE', 'RESULTS', 'RESUMED',
  'RESUMES', 'RETAILS', 'RETAINS', 'RETCH', 'RETIRED', 'RETIRES', 'RETREAT', 'RETRO', 'RETRY', 'RETURNS', 'REUSE', 'REVEALS',
  'REVEL', 'REVENUE', 'REVERSE', 'REVIEWS', 'REVISED', 'REVIVAL', 'REVUE', 'REWARDS', 'RHINO', 'RHYME', 'RHYTHMS', 'RIB',
  'RIBBONS', 'RIBS', 'RICE', 'RICH', 'RID', 'RIDDLES', 'RIDE', 'RIDER', 'RIDGE', 'RIFE', 'RIFF', 'RIFLE',
  'RIFT', 'RIG', 'RIGHT', 'RIGID', 'RIGOR', 'RIGS', 'RILE', 'RIM', 'RIMS', 'RIND', 'RING', 'RINK',
  'RINSE', 'RIOT', 'RIP', 'RIPE', 'RIPEN', 'RIPER', 'RIPS', 'RISE', 'RISEN', 'RISER', 'RISK', 'RISKY',
  'RITE', 'RITZ', 'RIVAL', 'RIVALRY', 'RIVER', 'RIVET', 'ROACH', 'ROAD', 'ROADWAY', 'ROAM', 'ROAR', 'ROAST',
  'ROASTED', 'ROB', 'ROBBERY', 'ROBE', 'ROBIN', 'ROBOT', 'ROBOTIC', 'ROBS', 'ROCK', 'ROCKY', 'ROD', 'RODE',
  'RODEO', 'RODS', 'ROE', 'ROES', 'ROGER', 'ROGUE', 'ROLE', 'ROLL', 'ROLLERS', 'ROLLING', 'ROMANCE', 'ROMP',
  'ROOF', 'ROOFTOP', 'ROOK', 'ROOM', 'ROOMY', 'ROOST', 'ROOT', 'ROPE', 'ROPY', 'ROSE', 'ROSY', 'ROT',
  'ROTE', 'ROTOR', 'ROTS', 'ROUGE', 'ROUGH', 'ROUND', 'ROUSE', 'ROUT', 'ROUTE', 'ROUTINE', 'ROUTING', 'ROVE',
  'ROVER', 'ROW', 'ROWDY', 'ROWER', 'ROWS', 'ROYAL', 'ROYALTY', 'RUB', 'RUBE', 'RUBS', 'RUBY', 'RUDDY',
  'RUDE', 'RUDER', 'RUFF', 'RUG', 'RUGBY', 'RUGS', 'RUIN', 'RULE', 'RULER', 'RUMBA', 'RUMOR', 'RUMP',
  'RUMS', 'RUN', 'RUNG', 'RUNNERS', 'RUNNING', 'RUNS', 'RUNT', 'RUPEE', 'RURAL', 'RUSE', 'RUSH', 'RUSHING',
  'RUST', 'RUSTING', 'RUSTY', 'RUT', 'RUTS', 'RYE', 'SACK', 'SAD', 'SADLY', 'SAFE', 'SAFER', 'SAG',
  'SAGA', 'SAGE', 'SAID', 'SAIL', 'SAILING', 'SAILORS', 'SAINT', 'SAKE', 'SALAD', 'SALE', 'SALLY', 'SALMONS',
  'SALON', 'SALSA', 'SALT', 'SALTY', 'SALVE', 'SALVO', 'SAME', 'SAMPLES', 'SANCTUM', 'SAND', 'SANDALS', 'SANDY',
  'SANE', 'SANER', 'SANG', 'SANK', 'SANS', 'SAP', 'SAPPY', 'SAPS', 'SASH', 'SASS', 'SASSY', 'SAT',
  'SATE', 'SATIN', 'SATYR', 'SAUCE', 'SAUCY', 'SAUNA', 'SAUTE', 'SAVE', 'SAVINGS', 'SAVOR', 'SAVOY', 'SAVVY',
  'SAW', 'SAWS', 'SAY', 'SAYS', 'SCAB', 'SCALD', 'SCALE', 'SCALP', 'SCALY', 'SCAM', 'SCAMP', 'SCAN',
  'SCANDAL', 'SCANT', 'SCAR', 'SCARE', 'SCARF', 'SCARLET', 'SCARY', 'SCAT', 'SCENE', 'SCENERY', 'SCENT', 'SCHOLAR',
  'SCIENCE', 'SCION', 'SCOFF', 'SCOLD', 'SCONE', 'SCOOP', 'SCOOTER', 'SCOPE', 'SCORE', 'SCORN', 'SCOT', 'SCOUR',
  'SCOUT', 'SCOWL', 'SCRAM', 'SCRAP', 'SCRAPED', 'SCRATCH', 'SCREAMS', 'SCREENS', 'SCREW', 'SCRUB', 'SCRUM', 'SCUBA',
  'SEA', 'SEAFOOD', 'SEAL', 'SEALING', 'SEAM', 'SEAR', 'SEAS', 'SEASONS', 'SEAT', 'SECRECY', 'SECRETS', 'SECS',
  'SECT', 'SECTION', 'SECULAR', 'SECURED', 'SECURES', 'SEDAN', 'SEE', 'SEED', 'SEEDY', 'SEEK', 'SEEKING', 'SEEM',
  'SEEN', 'SEEP', 'SEER', 'SEES', 'SEGMENT', 'SEGUE', 'SEIZE', 'SELECTS', 'SELF', 'SELL', 'SEMEN', 'SEMI',
  'SENATOR', 'SEND', 'SENDING', 'SENIORS', 'SENSE', 'SENSORS', 'SENSORY', 'SENT', 'SEPIA', 'SEQUELS', 'SERF', 'SERIF',
  'SERIOUS', 'SERMONS', 'SERUM', 'SERVANT', 'SERVE', 'SERVERS', 'SERVICE', 'SERVING', 'SET', 'SETS', 'SETTLER', 'SETUP',
  'SEVEN', 'SEVENTH', 'SEVENTY', 'SEVER', 'SEVERAL', 'SEW', 'SEWER', 'SEWN', 'SEWS', 'SHACK', 'SHAD', 'SHADE',
  'SHADOWS', 'SHADY', 'SHAFT', 'SHAG', 'SHAH', 'SHAKE', 'SHAKING', 'SHAKY', 'SHALE', 'SHALL', 'SHALLOW', 'SHALT',
  'SHAM', 'SHAME', 'SHANK', 'SHAPE', 'SHAPING', 'SHARD', 'SHARE', 'SHARING', 'SHARK', 'SHARP', 'SHAVE', 'SHAWL',
  'SHE', 'SHEAF', 'SHEAR', 'SHED', 'SHEEN', 'SHEEP', 'SHEER', 'SHEET', 'SHEIK', 'SHELF', 'SHELL', 'SHELTER',
  'SHIED', 'SHIFT', 'SHIN', 'SHINE', 'SHINING', 'SHINY', 'SHIP', 'SHIPPED', 'SHIRE', 'SHIRK', 'SHIRT', 'SHIV',
  'SHOAL', 'SHOCK', 'SHOCKED', 'SHOE', 'SHONE', 'SHOO', 'SHOOK', 'SHOOT', 'SHOP', 'SHORE', 'SHORN', 'SHORT',
  'SHORTEN', 'SHORTER', 'SHORTLY', 'SHOT', 'SHOUT', 'SHOVE', 'SHOW', 'SHOWERS', 'SHOWING', 'SHOWN', 'SHOWY', 'SHREW',
  'SHRUB', 'SHRUG', 'SHUCK', 'SHUN', 'SHUNT', 'SHUSH', 'SHUT', 'SHUTTER', 'SHY', 'SHYLY', 'SIBLING', 'SICK',
  'SIDE', 'SIDEBAR', 'SIEGE', 'SIEVE', 'SIFT', 'SIGH', 'SIGHT', 'SIGMA', 'SIGN', 'SIGNALS', 'SIGNING', 'SILENCE',
  'SILK', 'SILKY', 'SILL', 'SILLY', 'SILO', 'SILT', 'SILVER', 'SILVERS', 'SIMILAR', 'SIN', 'SINCE', 'SINCERE',
  'SINE', 'SINEW', 'SING', 'SINGE', 'SINGERS', 'SINGING', 'SINK', 'SINKING', 'SINS', 'SIP', 'SIPS', 'SIR',
  'SIRE', 'SIREN', 'SIRS', 'SIS', 'SISSY', 'SISTERS', 'SIT', 'SITE', 'SITS', 'SIX', 'SIXTH', 'SIXTY',
  'SIZE', 'SKATE', 'SKEW', 'SKI', 'SKID', 'SKIER', 'SKIFF', 'SKILL', 'SKILLED', 'SKIM', 'SKIMP', 'SKIN',
  'SKINNER', 'SKIP', 'SKIRT', 'SKIS', 'SKIT', 'SKULK', 'SKULL', 'SKUNK', 'SKY', 'SLAB', 'SLACK', 'SLAG',
  'SLAIN', 'SLAM', 'SLANG', 'SLANT', 'SLAP', 'SLASH', 'SLAT', 'SLATE', 'SLAVERY', 'SLAY', 'SLED', 'SLEEK',
  'SLEEP', 'SLEET', 'SLEEVES', 'SLENDER', 'SLEPT', 'SLEW', 'SLICE', 'SLICK', 'SLID', 'SLIDE', 'SLIDERS', 'SLIDING',
  'SLIGHTS', 'SLIM', 'SLIME', 'SLIMY', 'SLING', 'SLINK', 'SLIP', 'SLIPPED', 'SLIPPER', 'SLIT', 'SLOB', 'SLOG',
  'SLOOP', 'SLOP', 'SLOPE', 'SLOSH', 'SLOT', 'SLOTH', 'SLOW', 'SLOWEST', 'SLOWING', 'SLUG', 'SLUM', 'SLUMP',
  'SLUNG', 'SLUNK', 'SLUR', 'SLURP', 'SLUSH', 'SLY', 'SLYLY', 'SMACK', 'SMALL', 'SMART', 'SMASH', 'SMEAR',
  'SMELL', 'SMELT', 'SMILE', 'SMILING', 'SMIRK', 'SMITE', 'SMITH', 'SMOCK', 'SMOG', 'SMOKE', 'SMOKING', 'SMOKY',
  'SMOTE', 'SMUG', 'SMUT', 'SNACK', 'SNAG', 'SNAIL', 'SNAKE', 'SNAKY', 'SNAP', 'SNARE', 'SNARL', 'SNEAK',
  'SNEER', 'SNIDE', 'SNIFF', 'SNIP', 'SNIPE', 'SNOB', 'SNOOP', 'SNORE', 'SNORT', 'SNOT', 'SNOUT', 'SNOW',
  'SNOWY', 'SNUB', 'SNUCK', 'SNUFF', 'SNUG', 'SOAK', 'SOAP', 'SOAPY', 'SOAR', 'SOB', 'SOBER', 'SOBS',
  'SOCK', 'SOD', 'SODA', 'SOFA', 'SOFT', 'SOGGY', 'SOIL', 'SOLAR', 'SOLD', 'SOLDIER', 'SOLE', 'SOLID',
  'SOLO', 'SOLVE', 'SOLVING', 'SOME', 'SOMEHOW', 'SOMEONE', 'SON', 'SONAR', 'SONG', 'SONIC', 'SONS', 'SOON',
  'SOOT', 'SOOTH', 'SOOTY', 'SOP', 'SORE', 'SORROWS', 'SORRY', 'SORT', 'SORTING', 'SOUL', 'SOUND', 'SOUP',
  'SOUR', 'SOUTH', 'SOW', 'SOWN', 'SOWS', 'SOY', 'SPA', 'SPACE', 'SPADE', 'SPAM', 'SPAN', 'SPANK',
  'SPAR', 'SPARE', 'SPARK', 'SPARKLE', 'SPASM', 'SPAT', 'SPATIAL', 'SPAWN', 'SPAY', 'SPEAK', 'SPEAKER', 'SPEAR',
  'SPEC', 'SPECIAL', 'SPECIES', 'SPECIFY', 'SPECK', 'SPECTOR', 'SPED', 'SPEED', 'SPEEDED', 'SPELL', 'SPELT', 'SPEND',
  'SPENT', 'SPERM', 'SPEW', 'SPICE', 'SPICY', 'SPIED', 'SPIEL', 'SPIKE', 'SPIKY', 'SPILL', 'SPILT', 'SPIN',
  'SPINACH', 'SPINDLE', 'SPINE', 'SPINY', 'SPIRE', 'SPIRITS', 'SPIT', 'SPITE', 'SPLAT', 'SPLIT', 'SPOIL', 'SPOKE',
  'SPONSOR', 'SPOOF', 'SPOOK', 'SPOOL', 'SPOON', 'SPORE', 'SPORT', 'SPOT', 'SPOTTED', 'SPOUT', 'SPRAY', 'SPREADS',
  'SPREE', 'SPRIG', 'SPRING', 'SPRINGS', 'SPRY', 'SPUD', 'SPUN', 'SPUR', 'SPURT', 'SPY', 'SQUAD', 'SQUAT',
  'SQUIB', 'STAB', 'STACK', 'STADIUM', 'STAFF', 'STAG', 'STAGE', 'STAID', 'STAIN', 'STAINED', 'STAIR', 'STAKE',
  'STALE', 'STALK', 'STALKER', 'STALL', 'STAMP', 'STAND', 'STANK', 'STAPLER', 'STAR', 'STARE', 'STARK', 'START',
  'STARTLE', 'STARTUP', 'STARVED', 'STASH', 'STAT', 'STATE', 'STATING', 'STATION', 'STATUES', 'STATURE', 'STATUTE', 'STAVE',
  'STAY', 'STEAD', 'STEAK', 'STEAL', 'STEALTH', 'STEAM', 'STEAMER', 'STEED', 'STEEL', 'STEEP', 'STEER', 'STEIN',
  'STEM', 'STEP', 'STERN', 'STEW', 'STICK', 'STICKER', 'STIFF', 'STILL', 'STILT', 'STING', 'STINK', 'STINT',
  'STIR', 'STIRRED', 'STOCK', 'STOIC', 'STOKE', 'STOLE', 'STOMACH', 'STOMP', 'STONE', 'STONY', 'STOOD', 'STOOL',
  'STOOP', 'STOP', 'STORAGE', 'STORE', 'STORIES', 'STORK', 'STORM', 'STORMED', 'STORY', 'STOUT', 'STOVE', 'STOW',
  'STRANGE', 'STRAP', 'STRAW', 'STRAY', 'STREAMS', 'STREETS', 'STRETCH', 'STRIKER', 'STRIP', 'STRIPES', 'STRUT', 'STUB',
  'STUCK', 'STUD', 'STUDENT', 'STUDIED', 'STUDIES', 'STUDY', 'STUFF', 'STUMP', 'STUN', 'STUNG', 'STUNK', 'STUNT',
  'STYLE', 'SUAVE', 'SUB', 'SUBJECT', 'SUCCEED', 'SUCCESS', 'SUCH', 'SUCK', 'SUCTION', 'SUE', 'SUES', 'SUFFERS',
  'SUGAR', 'SUGGEST', 'SUIT', 'SUITE', 'SUITORS', 'SULK', 'SULKY', 'SULLY', 'SUM', 'SUMAC', 'SUMMARY', 'SUMMERS',
  'SUMO', 'SUMS', 'SUN', 'SUNBEAM', 'SUNG', 'SUNK', 'SUNNY', 'SUNRISE', 'SUNS', 'SUPER', 'SUPPORT', 'SUPPOSE',
  'SUPREME', 'SURE', 'SURER', 'SURF', 'SURFACE', 'SURGE', 'SURGEON', 'SURGERY', 'SURLY', 'SURNAME', 'SURPLUS', 'SURVEYS',
  'SURVIVE', 'SUSHI', 'SUSPECT', 'SUSTAIN', 'SWAB', 'SWAM', 'SWAMI', 'SWAMP', 'SWAN', 'SWAP', 'SWARM', 'SWASH',
  'SWAT', 'SWATH', 'SWAY', 'SWEAR', 'SWEAT', 'SWEATER', 'SWEEP', 'SWEET', 'SWEETEN', 'SWEETER', 'SWELL', 'SWEPT',
  'SWIFT', 'SWIFTER', 'SWIG', 'SWILL', 'SWIM', 'SWIMMER', 'SWINE', 'SWING', 'SWIRL', 'SWISH', 'SWOON', 'SWOOP',
  'SWORD', 'SWORE', 'SWORN', 'SWUM', 'SWUNG', 'SYMBOLS', 'SYMPTOM', 'SYNAPSE', 'SYNC', 'SYNOD', 'SYRUP', 'SYSTEMS',
  'TAB', 'TABBY', 'TABLE', 'TABOO', 'TABS', 'TACIT', 'TACK', 'TACKY', 'TACT', 'TACTICS', 'TAFFY', 'TAG',
  'TAGS', 'TAIL', 'TAINT', 'TAKE', 'TAKEN', 'TAKER', 'TALE', 'TALENTS', 'TALK', 'TALKING', 'TALL', 'TALLY',
  'TALON', 'TAME', 'TAMER', 'TAMP', 'TAMS', 'TAN', 'TANGLED', 'TANGO', 'TANGY', 'TANK', 'TANS', 'TAP',
  'TAPE', 'TAPER', 'TAPIR', 'TAPS', 'TAR', 'TARDY', 'TARE', 'TARGETS', 'TARIFFS', 'TAROT', 'TART', 'TASK',
  'TASTE', 'TASTING', 'TASTY', 'TAT', 'TATTY', 'TAUNT', 'TAWNY', 'TAX', 'TAXI', 'TEA', 'TEACH', 'TEACHER',
  'TEAK', 'TEAL', 'TEAM', 'TEAR', 'TEARY', 'TEAS', 'TEASE', 'TEASING', 'TEAT', 'TEDDY', 'TEE', 'TEEM',
  'TEEN', 'TEETH', 'TELECOM', 'TELL', 'TEMPEST', 'TEMPLES', 'TEMPO', 'TEN', 'TEND', 'TENDERS', 'TENET', 'TENOR',
  'TENSE', 'TENSION', 'TENT', 'TENTH', 'TEPEE', 'TEPID', 'TERM', 'TERRA', 'TERRAIN', 'TERSE', 'TEST', 'TESTING',
  'TESTY', 'TEXT', 'TEXTURE', 'THAN', 'THANK', 'THAT', 'THAW', 'THE', 'THEATER', 'THEATRE', 'THEE', 'THEFT',
  'THEIR', 'THEM', 'THEME', 'THEN', 'THERAPY', 'THERE', 'THERMAL', 'THESE', 'THEY', 'THICK', 'THICKER', 'THICKLY',
  'THIEF', 'THIGH', 'THIN', 'THING', 'THINK', 'THINKER', 'THIRD', 'THIRSTY', 'THIS', 'THONG', 'THORN', 'THOSE',
  'THOU', 'THOUGHT', 'THREADS', 'THREATS', 'THREE', 'THREW', 'THRILLS', 'THRIVED', 'THRIVES', 'THRO', 'THROB', 'THROUGH',
  'THROW', 'THRUM', 'THUD', 'THUG', 'THUMB', 'THUMP', 'THUNDER', 'THY', 'THYME', 'TIARA', 'TIBIA', 'TIC',
  'TICK', 'TICKETS', 'TIDAL', 'TIDE', 'TIDY', 'TIE', 'TIED', 'TIER', 'TIES', 'TIGER', 'TIGHT', 'TILDE',
  'TILE', 'TILL', 'TILT', 'TIME', 'TIMER', 'TIMID', 'TIMIDLY', 'TIN', 'TINE', 'TINS', 'TINT', 'TINY',
  'TIP', 'TIPS', 'TIPSY', 'TIRE', 'TITAN', 'TITHE', 'TITLE', 'TITULAR', 'TOAD', 'TOAST', 'TOBACCO', 'TODAY',
  'TODDY', 'TOE', 'TOES', 'TOFU', 'TOGA', 'TOIL', 'TOKEN', 'TOLD', 'TOLL', 'TOMB', 'TOME', 'TON',
  'TONAL', 'TONE', 'TONGA', 'TONIC', 'TONIGHT', 'TONS', 'TOO', 'TOOK', 'TOOL', 'TOOLKIT', 'TOON', 'TOOT',
  'TOOTH', 'TOP', 'TOPAZ', 'TOPIC', 'TOPICAL', 'TOPS', 'TORCH', 'TORE', 'TORN', 'TORSO', 'TORT', 'TORTURE',
  'TORUS', 'TOSS', 'TOTAL', 'TOTALED', 'TOTE', 'TOTEM', 'TOTS', 'TOUCH', 'TOUCHED', 'TOUCHES', 'TOUGH', 'TOUR',
  'TOURIST', 'TOUT', 'TOW', 'TOWARDS', 'TOWEL', 'TOWER', 'TOWN', 'TOXIC', 'TOXIN', 'TOY', 'TOYS', 'TRACE',
  'TRACK', 'TRACKED', 'TRACKER', 'TRACT', 'TRADE', 'TRADERS', 'TRADING', 'TRAFFIC', 'TRAGEDY', 'TRAIL', 'TRAIN', 'TRAINED',
  'TRAINER', 'TRAIT', 'TRAM', 'TRAMP', 'TRANSIT', 'TRAP', 'TRASH', 'TRAVELS', 'TRAWL', 'TRAY', 'TREAD', 'TREASON',
  'TREAT', 'TREATED', 'TREE', 'TREK', 'TREMBLE', 'TREND', 'TRIAD', 'TRIAL', 'TRIBE', 'TRICE', 'TRICK', 'TRIED',
  'TRIGGER', 'TRIM', 'TRIO', 'TRIP', 'TRIPE', 'TRITE', 'TRIUMPH', 'TROD', 'TROLL', 'TROOP', 'TROPE', 'TROT',
  'TROUBLE', 'TROUT', 'TROVE', 'TRUCE', 'TRUCK', 'TRUE', 'TRUER', 'TRULY', 'TRUMP', 'TRUNK', 'TRUSS', 'TRUST',
  'TRUSTED', 'TRUTH', 'TRY', 'TRYST', 'TSUNAMI', 'TUB', 'TUBA', 'TUBAL', 'TUBE', 'TUBER', 'TUBS', 'TUCK',
  'TUFT', 'TUG', 'TUGS', 'TULIP', 'TULLE', 'TUMOR', 'TUNA', 'TUNE', 'TUNIC', 'TURBINE', 'TURBO', 'TURF',
  'TURKEYS', 'TURN', 'TURNING', 'TUSK', 'TUTOR', 'TWANG', 'TWEAK', 'TWEED', 'TWEET', 'TWICE', 'TWIG', 'TWIGS',
  'TWIN', 'TWINE', 'TWINKLE', 'TWIRL', 'TWIST', 'TWIT', 'TWO', 'TWOS', 'TYCO', 'TYING', 'TYPE', 'TYPICAL',
  'TYPO', 'UDDER', 'UGLIEST', 'UGLY', 'ULCER', 'ULTRA', 'UMBRA', 'UNAWARE', 'UNCLE', 'UNCLEAR', 'UNCUT', 'UNDER',
  'UNDERGO', 'UNDID', 'UNDO', 'UNDUE', 'UNFED', 'UNFIT', 'UNIFIED', 'UNIFORM', 'UNIFY', 'UNION', 'UNIT', 'UNITARY',
  'UNITE', 'UNITY', 'UNKNOWN', 'UNLATCH', 'UNLEASH', 'UNLIT', 'UNLUCKY', 'UNMET', 'UNMOVED', 'UNSET', 'UNTIE', 'UNTIL',
  'UNTO', 'UNTYING', 'UNUSUAL', 'UNWED', 'UNZIP', 'UPDATED', 'UPDATES', 'UPGRADE', 'UPON', 'UPPER', 'UPRIGHT', 'UPSET',
  'URBAN', 'URGE', 'URGENCY', 'URINE', 'URN', 'URNS', 'USAGE', 'USE', 'USED', 'USELESS', 'USER', 'USES',
  'USHER', 'USING', 'USUAL', 'USURP', 'UTENSIL', 'UTILE', 'UTILITY', 'UTTER', 'UTTERED', 'VACANCY', 'VACCINE', 'VACUUMS',
  'VAGUE', 'VAGUELY', 'VAIN', 'VALE', 'VALET', 'VALIANT', 'VALID', 'VALIDLY', 'VALLEYS', 'VALOR', 'VALUE', 'VALVE',
  'VAMP', 'VAN', 'VANE', 'VANILLA', 'VANS', 'VAPID', 'VAPOR', 'VARIETY', 'VARIOUS', 'VARY', 'VARYING', 'VASE',
  'VAST', 'VAT', 'VATS', 'VAULT', 'VAUNT', 'VEAL', 'VEER', 'VEGAN', 'VEHICLE', 'VEIL', 'VEIN', 'VENOM',
  'VENT', 'VENTURE', 'VENUE', 'VERB', 'VERDICT', 'VERGE', 'VERSE', 'VERSION', 'VERSO', 'VERVE', 'VERY', 'VEST',
  'VET', 'VETERAN', 'VETO', 'VETS', 'VIA', 'VIAL', 'VIBE', 'VIBRANT', 'VIBRATE', 'VICAR', 'VICE', 'VICTIMS',
  'VICTORS', 'VICTORY', 'VIDEO', 'VIE', 'VIEW', 'VIGIL', 'VIGOR', 'VILE', 'VILLA', 'VILLAGE', 'VILLAIN', 'VINE',
  'VINTAGE', 'VINYL', 'VIOLA', 'VIOLATE', 'VIOLENT', 'VIOLINS', 'VIPER', 'VIRAL', 'VIRTUAL', 'VIRTUES', 'VIRUS', 'VISA',
  'VISE', 'VISIBLE', 'VISIBLY', 'VISIONS', 'VISIT', 'VISITED', 'VISITOR', 'VISOR', 'VISTA', 'VISUALS', 'VITAL', 'VITAMIN',
  'VIVID', 'VIXEN', 'VOCAL', 'VODKA', 'VOGUE', 'VOICE', 'VOID', 'VOILA', 'VOLCANO', 'VOLT', 'VOMIT', 'VOTE',
  'VOTER', 'VOUCH', 'VOW', 'VOWEL', 'VOWS', 'VOYAGES', 'VULTURE', 'VYING', 'WACKY', 'WADE', 'WAFER', 'WAG',
  'WAGE', 'WAGER', 'WAGON', 'WAIF', 'WAIL', 'WAIST', 'WAIT', 'WAIVE', 'WAKE', 'WALK', 'WALKERS', 'WALKING',
  'WALL', 'WALTZ', 'WAND', 'WANDERS', 'WANE', 'WANT', 'WAR', 'WARD', 'WARE', 'WARFARE', 'WARM', 'WARMERS',
  'WARMEST', 'WARMING', 'WARN', 'WARNING', 'WARP', 'WARRIOR', 'WARS', 'WART', 'WARTY', 'WARY', 'WAS', 'WASH',
  'WASHERS', 'WASHING', 'WASP', 'WAST', 'WASTE', 'WASTING', 'WATCH', 'WATCHED', 'WATCHER', 'WATCHES', 'WATER', 'WATERED',
  'WAVE', 'WAVER', 'WAVY', 'WAX', 'WAXEN', 'WAY', 'WAYS', 'WAYWARD', 'WEAK', 'WEAKEST', 'WEAL', 'WEALTHY',
  'WEAN', 'WEAPONS', 'WEAR', 'WEARING', 'WEARY', 'WEATHER', 'WEAVE', 'WEAVERS', 'WEAVING', 'WEB', 'WEBS', 'WED',
  'WEDDING', 'WEDGE', 'WEDS', 'WEE', 'WEED', 'WEEDY', 'WEEK', 'WEEKDAY', 'WEEKEND', 'WEEP', 'WEIGH', 'WEIGHED',
  'WEIGHTS', 'WEIRD', 'WELCH', 'WELCOME', 'WELD', 'WELFARE', 'WELL', 'WELSH', 'WELT', 'WENT', 'WEPT', 'WERE',
  'WEST', 'WESTERN', 'WET', 'WETLAND', 'WETS', 'WETTING', 'WHACK', 'WHALE', 'WHARF', 'WHAT', 'WHEAT', 'WHEEL',
  'WHELP', 'WHEN', 'WHERE', 'WHEREBY', 'WHET', 'WHETHER', 'WHICH', 'WHIFF', 'WHILE', 'WHIM', 'WHINE', 'WHINY',
  'WHIP', 'WHIRL', 'WHISK', 'WHISPER', 'WHISTLE', 'WHITE', 'WHIZ', 'WHO', 'WHOA', 'WHOEVER', 'WHOLE', 'WHOM',
  'WHOOP', 'WHORE', 'WHOSE', 'WHY', 'WHYS', 'WICK', 'WIDE', 'WIDEN', 'WIDENED', 'WIDER', 'WIDOW', 'WIDOWED',
  'WIDTH', 'WIELD', 'WIFE', 'WIG', 'WIGHT', 'WIGS', 'WILD', 'WILL', 'WILLING', 'WILLY', 'WILT', 'WILY',
  'WIMPY', 'WIN', 'WINCE', 'WINCH', 'WIND', 'WINDING', 'WINDOWS', 'WINDY', 'WINE', 'WING', 'WINK', 'WINNERS',
  'WINNING', 'WINS', 'WINTERS', 'WIPE', 'WIRE', 'WIRY', 'WISE', 'WISER', 'WISH', 'WISHING', 'WISP', 'WISPY',
  'WIT', 'WITCH', 'WITH', 'WITHOUT', 'WITNESS', 'WITS', 'WITTY', 'WOBBLED', 'WOE', 'WOES', 'WOK', 'WOKE',
  'WOKEN', 'WOLF', 'WOMAN', 'WOMB', 'WOMEN', 'WON', 'WONDERS', 'WONT', 'WOO', 'WOOD', 'WOODY', 'WOOER',
  'WOOF', 'WOOL', 'WOOLY', 'WOOZY', 'WORD', 'WORDY', 'WORE', 'WORK', 'WORKERS', 'WORKING', 'WORKOUT', 'WORLD',
  'WORM', 'WORN', 'WORRIED', 'WORRIES', 'WORRY', 'WORSE', 'WORSHIP', 'WORST', 'WORTH', 'WOULD', 'WOUND', 'WOUNDED',
  'WOVE', 'WOVEN', 'WOW', 'WRACK', 'WRAP', 'WRATH', 'WREAK', 'WRECK', 'WRECKED', 'WREN', 'WREST', 'WRING',
  'WRIST', 'WRIT', 'WRITE', 'WRITERS', 'WRITING', 'WRITTEN', 'WRONG', 'WRONGLY', 'WROTE', 'WRUNG', 'WRYLY', 'YACHT',
  'YAK', 'YAKS', 'YAM', 'YAMS', 'YANK', 'YAP', 'YARD', 'YARDAGE', 'YARN', 'YAWN', 'YAWNING', 'YEA',
  'YEAH', 'YEAR', 'YEARN', 'YEAS', 'YEAST', 'YELL', 'YELLOWS', 'YELP', 'YEN', 'YES', 'YET', 'YEW',
  'YIELD', 'YIELDED', 'YIP', 'YOGA', 'YOKE', 'YOLK', 'YORE', 'YOU', 'YOUNG', 'YOUNGER', 'YOUR', 'YOUTH',
  'ZAP', 'ZEALOUS', 'ZEBRA', 'ZEN', 'ZERO', 'ZEST', 'ZESTY', 'ZINC', 'ZIP', 'ZIPPERS', 'ZONAL', 'ZONE',
  'ZOO', 'ZOOM',
]);


/**
 * Checks if a word can be legally formed using only available letters from root.
 * Respects character counts (frequency of each letter).
 *
 * @param {string} word
 * @param {string} root
 * @returns {boolean}
 */
export function canFormFromRoot(word, root) {
  if (!root) return true;
  const available = {};
  for (const ch of String(root).toUpperCase()) {
    available[ch] = (available[ch] || 0) + 1;
  }
  for (const ch of String(word).toUpperCase()) {
    if (!available[ch]) return false;
    available[ch]--;
  }
  return true;
}

/**
 * Shuffles an array of letters with the Fisher-Yates algorithm.
 * Guarantees that the shuffled order does not match the exact input if length > 1.
 *
 * @param {string[] | string} letters
 * @returns {string[]}
 */
export function shuffleLetters(letters) {
  const arr = Array.isArray(letters) ? [...letters] : letters.split('');
  if (arr.length <= 1) return arr;

  const originalStr = arr.join('');
  let attempts = 0;

  do {
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      const temp = arr[i];
      arr[i] = arr[j];
      arr[j] = temp;
    }
    attempts++;
  } while (arr.join('') === originalStr && attempts < 10);

  return arr;
}

/**
 * Groups a list of words by their character length.
 *
 * @param {string[]} words
 * @returns {Record<number, string[]>}
 */
export function groupWordsByLength(words) {
  const groups = {};
  for (const word of words) {
    const len = word.length;
    if (!groups[len]) {
      groups[len] = [];
    }
    groups[len].push(word);
  }
  for (const len in groups) {
    groups[len].sort((a, b) => a.localeCompare(b));
  }
  return groups;
}

/**
 * Generates a puzzle for the chosen difficulty tier.
 *
 * @param {string} tier 'beginner' | 'intermediate' | 'master'
 * @param {number} puzzleIndex
 * @returns {object} puzzle metadata
 */
export function generatePuzzle(tier = 'beginner', puzzleIndex = 0) {
  const tierPuzzles = ANAGRAM_PUZZLES[tier] || ANAGRAM_PUZZLES.beginner;
  const safeIdx = Math.max(0, Math.min(puzzleIndex, tierPuzzles.length - 1));
  const data = tierPuzzles[safeIdx];

  const root = data.root.toUpperCase();
  const targetWords = [...data.targets].map((w) => w.toUpperCase());
  const extraWords = (data.extras || []).map((w) => w.toUpperCase());
  const allValidWords = new Set([...targetWords, ...extraWords]);

  const scrambledLetters = shuffleLetters(root);

  return {
    id: data.id,
    root,
    tier,
    index: safeIdx,
    totalInTier: tierPuzzles.length,
    scrambledLetters,
    targetWords,
    groupedTargets: groupWordsByLength(targetWords),
    allValidWords: Array.from(allValidWords),
  };
}

/**
 * Validates a submitted word guess.
 *
 * Validation rules:
 * 1. Must only use available letters from the current root word (respecting letter frequencies).
 *    Returns status 'invalid' with message "Cannot be formed from available letters." if illegal.
 * 2. If length < 3, returns status 'too_short'.
 * 3. If already discovered in foundWords, returns status 'already_found'.
 * 4. If in targetWords, returns status 'valid_target'.
 * 5. If present in the comprehensive dictionary OR in the puzzle's extras/allValidWords,
 *    returns status 'valid_extra' with message "${normalized} is a valid bonus word!".
 * 6. Only returns 'invalid' if it is truly not a recognized English word.
 *
 * @param {string} guess Player's submitted string
 * @param {string[]} targetWords Curated target words to uncover
 * @param {string[]} foundWords Words already discovered
 * @param {string[]} allValidWords All words accepted (including extras)
 * @param {string} [root] The root word for the puzzle
 * @returns {{ status: 'too_short' | 'already_found' | 'valid_target' | 'valid_extra' | 'invalid', word: string, message: string }}
 */
export function validateGuess(guess, targetWords = [], foundWords = [], allValidWords = [], root = '') {
  const normalized = String(guess || '').trim().toUpperCase();

  // Deduce root word if not directly supplied
  let rootLetters = root;
  if (!rootLetters) {
    const candidates = [...targetWords, ...allValidWords];
    for (const w of candidates) {
      if (!rootLetters || w.length > rootLetters.length) {
        rootLetters = w;
      }
    }
  }

  // 1. Check legal letter formation respecting character counts
  if (rootLetters && !canFormFromRoot(normalized, rootLetters)) {
    return {
      status: 'invalid',
      word: normalized,
      message: 'Cannot be formed from available letters.',
    };
  }

  // 2. Minimum length check
  if (normalized.length < 3) {
    return {
      status: 'too_short',
      word: normalized,
      message: 'Words must be at least 3 letters.',
    };
  }

  // 3. Already found check
  if (foundWords.includes(normalized)) {
    return {
      status: 'already_found',
      word: normalized,
      message: `${normalized} already discovered.`,
    };
  }

  // 4. Target word check
  if (targetWords.includes(normalized)) {
    return {
      status: 'valid_target',
      word: normalized,
      message: `Discovered ${normalized}!`,
    };
  }

  // 5. Bonus word check (offline comprehensive dictionary or puzzle extras)
  if (ANAGRAM_DICTIONARY.has(normalized) || allValidWords.includes(normalized)) {
    return {
      status: 'valid_extra',
      word: normalized,
      message: `${normalized} is a valid bonus word!`,
    };
  }

  // 6. Truly not a recognized English word
  return {
    status: 'invalid',
    word: normalized,
    message: `${normalized} is not a recognized English word.`,
  };
}
